### ISSUE TITLE
Support color themes?

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#161]
Would be neat to let people choose a color theme at some point. I feel like this is a subjective personal preference and not really an "option".

**Comment by jhthorsen** [comment]
This require a bit of work, but is supported in 7c6ff5b:

* Assetpack >=1.24 is required (script/convos install)
* cpanm CSS::Sass
* mkdir -p ~/.local/share/convos/assets/sass
* cat > ~/.local/share/convos/assets/sass/_variables.scss

    $body-bg: #111;
    $primary-color: color("green", "darken-4");
    $secondary-color: color("green", "darken-2");
    $header-color: color('green', 'lighten-3');
    $link-color: color("green", "lighten-2");
    $text-color: #777;

    $error-bg-color: color('red', 'lighten-5');
    $error-border-color: color('red', 'lighten-2');
    $error-text-color: color("red", "darken-4");
    $highlight-bg-color: lighten(color('red', 'lighten-5'), 5%);
    $notice-text-color: lighten($text-color, 40%);
    $notice-border-color: color('grey', 'lighten-1');
    $settings-active-color: #f6f6f6;

    $dialog-spacing: 4px;
    $readable-width: 50em;
    $main-menu-width: 240px;
    $sidebar-width: 320px;
    $z-index-header: 900;
    ^C

* Restart convos

The example theme above looks awful, but it works as an example imho.

Will document and/or re-open this issue if someone asks for this feature and it doesn't work as they expect.
