### ISSUE TITLE
Implement search in frontend and use of real database storage in backend

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#187]
I would like to add support for Postgres/SQLite/MySQL in the backend and then add search in the frontend. The search inside plain files are too slow and unusable, so it wont't work.

This issue will also implement what is requested in the issues below, since using an indexed storage backend will allow us to save mor data:

* #303 - Clicking on a notification element should take you to the correct place in the dialog
* #355 - Joins, parts, quits and nick changes not being displayed
* #374 - Show mode changes

**Comment by jhthorsen** [comment]
This is implemented in the backend: https://github.com/Nordaaker/convos/blob/one-point-oh/t/backend-file-messages.t

**Comment by SvetlanaTkachenko** [comment]
I would be glad to have this feature, too.

**Comment by Wikiwide** [comment]
Would be nice, as well.
Thank you.

**Comment by jhthorsen** [comment]
Guess we'll have a very basic search feature in a while... Going to get complaints, but it's a starting point 😄

**Comment by jhthorsen** [comment]
Going to close this issue and rather create a new one for SQL based backend.
