### ISSUE TITLE
Remove joins/parts/quits from output

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#189]
I don't think these are really valuable.

**Comment by jhthorsen** [comment]
Not sure how this will work with "smart" display... How do you know if we should show "join" or not? I think I want message "timeout" instead, so all the "notice" messages are hidden after 10 minutes. What do you think?

Also, these messages are not stored in the file based backend. Not sure if I want them stored either.

**Comment by jhthorsen** [comment]
I don't consider this important enough. Please re-open if you plan to actually fix it.
