### ISSUE TITLE
Add audio and video support using WebRTC

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#204]
Would be cool to be able to share desktop, do video and voice using WebRTC.

- http://www.webrtc.org/
- https://webrtc.github.io/samples/
- https://webrtc.github.io/samples/src/content/peerconnection/multiple/
- https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/audio/js/main.js

**Comment by jhthorsen** [comment]
I want to make a better integration with appear.in instead.

**Comment by poVoq** [comment]
How about Jitsi Meet integration instead? Its fully open source, can be self hosted and there is an easy to use javascript library for integrations.

**Comment by jhthorsen** [comment]
Jitsi is not related to this issue.

**Comment by poVoq** [comment]
Well, you mentioned appear.in which is pretty similar to Jitsi Meet.

**Comment by jhthorsen** [comment]
That was a reason for closing this issue, but I’ve since then decided to reopen it.

**Comment by jhthorsen** [comment]
Current work can be found in https://github.com/Nordaaker/convos/compare/jhthorsen/204-webrtc

Help is more than welcome, since it's not even close to be working.

- [ ] Figure out a good way to set up https://github.com/coturn/coturn, or a similar service. Looks like it needs TLS to work with WebRTC?
- [ ] Figure out if a default STUN server can be used, and if WebRTC can work in any case, without a TURN server. If so, is that browser dependent?
- [ ] Comment on https://github.com/Nordaaker/convos/blob/2b2d6ec4e048a7fe1ea5bf9856f6b4c5a950898e/assets/store/WebRTC.js
- [ ] Figure out if there's another library (other than webrtc-adapter that Convos can depend on
- [ ] Next iteration will have a shareable video link, so other non-convos users can join in. Currently the users need to be on the same network, registered to the same Convos installation.
- [ ] Move stun/turn configuration from environment variables to the web interface?
- [ ] Add error messages if turn/stun is not set up correctly
- [ ] The video chat is currently inside `DialogSettings.svelte`, but I expect it to be part of the main chat dialog later on, or maybe get it's own dedicated sidebar.

**Comment by poVoq** [comment]
TURN server is optional for special problematic clients with strict firewall settings and such.

**Comment by jhthorsen** [comment]
@poVoq: Are you 100% sure about that? I tested my code between two browsers locally (chrome and Firefox), behind the same (home) router, and they couldn't connect without a TURN server.

I'm not ruling out that my code is crazy buggy, but it seems strange that Firefox dev-console told me to add a TURN server.

**Comment by poVoq** [comment]
Yes, 100% but apparently you have one of those problematic setups.

I think this article explains it well (a bit down):
https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

**Comment by jhthorsen** [comment]
https://github.com/Nordaaker/convos/compare/jhthorsen/204-webrtc currently looks like this:

<img width="590" alt="bKaCcHcPhD2KyyAb" src="https://user-images.githubusercontent.com/45729/82132089-0abc3e00-9817-11ea-992d-c8094cbb2279.png">

Next up is to...

- [ ] Enable the video controls to actually mute audio/video
- [ ] Show video overlay and/or full screen (zoom button)
- [ ] Add error/loading indicator inside the video container
- [ ] Add a message to the conversation when someone starts a video conversation

**Comment by alectrocute** [comment]
You need a TURN server. Luckily, there's quite a few respectable and secure public servers (see: Google TURN)

**Comment by alectrocute** [comment]
Looking good, @jhthorsen!

**Comment by jhthorsen** [comment]
I'm going to close this issue now, since the basic implementation is in place.

**Comment by jhthorsen** [comment]
I'm going to re-open the issue, since the current implementation is not very good. Need to make a better solution before looking at #472, #473 and #474.

I am considering making the backend pluggable so you can choose between Jitsi and a Coturn based solution.

This issue also replaces #498.

**Comment by poVoq** [comment]
Well, while Jitsi is easy to use, it is to be honest also not very good and you end up running a XMPP server just for using it.

Maybe a better option is to use a webrtc gateway directly? Something like Janus: https://github.com/meetecho/janus-gateway seems popular and is for example used by Nextcloud Talk: https://github.com/strukturag/nextcloud-spreed-signaling

**Comment by jhthorsen** [comment]
@poVoq: Good points, but I don't have enough time to implement the integration myself.

Closing this issue, since doing a proper WebRTC implementation with limited development hours is not possible.

**Comment by jhthorsen** [comment]
I welcome a PR ❤️

**Comment by jhthorsen** [comment]
This is no longer an issue after #536.
