### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#21]
I would like to have a restricted version of Convos, which only lets you log in and join a channel, without settings or persistence. For running a demo mode and embedding in company pages.

**Comment by jhthorsen** [comment]
See also https://github.com/Nordaaker/convos/issues/89

**Comment by jhthorsen** [comment]
My idea is to use JWT (JSON web tokens) with enough information for a user to register and automatically join a server/chat room.

The payload of the JWT is a JSON structure with information, such as username, server and dialog/channel name. The signature is a checksum which the server can use to validate the payload. This means that unless the token was generated from a secure party, then Convos (or any JWT party) will reject the whole token.

The last part about "kiosk mode" is that the actual user interface will be stripped down. Like not having any menus. I would do that part by another query parameter, like "?kiosk=1", or maybe even a list of elements to show, like "?kiosk=participants,heading". Using such a parameter will then make convos render nicely inside an iframe.

**Comment by jhthorsen** [comment]
Closing this in favour of #346. (Because of age)
