### ISSUE TITLE
"Use of uninitialized value" error when starting daemon

### ISSUE THREAD

**Issue by lachenmayer** [Nordaaker/convos#230]
Hi, I just freshly installed convos, and I get the following error when I try to start the daemon using the magic incantation offered in the manual:

    $ ./vendor/bin/carton exec script/convos daemon --listen http://*:8080
    Use of uninitialized value in -f at /home/harry/convos/local/lib/perl5/Daemon/Control.pm line 313.
    Use of uninitialized value in open at /home/harry/convos/local/lib/perl5/Daemon/Control.pm line 299.
    Use of uninitialized value in concatenation (.) or string at /home/harry/convos/local/lib/perl5/Daemon/Control.pm line 299.
    Failed to write : No such file or directory at /home/harry/convos/local/lib/perl5/Daemon/Control.pm line 299.

Running this on a pretty bare-bones Ubuntu 14.04 VM btw.
Any ideas what could have gone wrong here? Cheers!
-harry

**Comment by jhthorsen** [comment]
This should be fixed by d4292fff9ea2394c091106add5066e73b4448df2.

Please re-open if I am wrong.
