### ISSUE TITLE
Convos will not start

### ISSUE THREAD

**Issue by gbyers** [Nordaaker/convos#232]
ircanywhere@geordienorman:~/convos$ ./vendor/bin/carton exec script/convos daemon --listen http://*:8080
[Mon Dec  8 00:24:13 2014] [info] Starting convos backend.
[Mon Dec  8 00:24:13 2014] [info] Listening at "http://*:8080".
Server available at http://127.0.0.1:8080.
[Mon Dec  8 00:24:13 2014] [error] [core:control] Stopping Mojo::IOLoop on 'core:control' error: Connection refused 
[Mon Dec  8 00:24:13 2014] [error] [REDIS ERROR] Connection refused

**Comment by jhthorsen** [comment]
@gbyers: Seems like redis is not running or not installed.
