### ISSUE TITLE
Convos does not respond to CTCP commands

### ISSUE THREAD

**Issue by danielamaya** [Nordaaker/convos#233]
Convos client does not respond to any CTCP commands. I am using Mojo::IRC 0.13 and Convos 0.8602. Here's the output from my tests (imatesting is using Convos):

> \>imatesting< CTCP VERSION
> \>damaya< CTCP VERSION
> \* Received a CTCP VERSION from damaya
> \-damaya- VERSION xchat 2.8.8 Linux 3.17.2-1-ARCH [x86_64/1.20GHz/SMP]
> \>damaya< CTCP TIME
> \* Received a CTCP TIME from damaya
> \-damaya- TIME Fri Dec 12 23:14:27
> \>damaya< CTCP PING
> \* Received a CTCP PING from damaya
> \* Ping reply from damaya: ? second(s)
> \>imatesting< CTCP TIME
> \>imatesting< CTCP PING

**Comment by jhthorsen** [comment]
I think this is fixed in https://github.com/jhthorsen/mojo-irc/pull/18. Please let me know if I'm wrong.
