### ISSUE TITLE
Combination of xml_escape + URI::Find leads to extracting URIs incorrectly

### ISSUE THREAD

**Issue by zmughal** [Nordaaker/convos#236]
As seen [here](https://github.com/Nordaaker/convos/blob/bf66844f4b51f002f2c9df622f84a9d8ee1cc096/lib/Convos/Plugin/Helpers.pm#L187), Convos uses

```perl
  $message->{message} = Mojo::Util::xml_escape($message->{message});

  URI::Find->new(
    sub {
      my $url = Mojo::Util::html_unescape(shift . '');
      $c->link_to($url, $url, target => '_blank', @class);
    }
  )->find(\$message->{message});
```

What this does for URIs linked using angle bracket delimiters (`<URL>`) as recommended by [RFC 3986](http://tools.ietf.org/html/rfc3986#appendix-C) is the following:

```perl
use v5.16;
use URI::Find;
use Mojo::Util;

my $msg_raw = 'before <https://github.com/Nordaaker/convos> after'; 
my $msg_xml_escape = Mojo::Util::xml_escape($msg_raw);

my $find = URI::Find->new( sub { "|@{[shift]}|"; } );
$find->find( \$msg_raw );
$find->find( \$msg_xml_escape );

say $msg_raw;
# before <|https://github.com/Nordaaker/convos|> after
say $msg_xml_escape;
# before &lt;|https://github.com/Nordaaker/convos&gt;| after
```

This is unexpected when all I want to do is make sure the URIs are parsed correctly! :-P

CC: @jberger

**Comment by jhthorsen** [comment]
I don't get it... Is the fix to call Mojo::Util::xml_escape() after we have extracted all the links? Got any input here @jberger?

**Comment by jberger** [comment]
I think the obvious first course of action is to turn the report into a failing test. I shall attempt it soon (I hope, ping me if I don't)

**Comment by jhthorsen** [comment]
This exact issue is not reproducible in the [next version](https://github.com/Nordaaker/convos/blob/batcode/assets/riot/dialog-message.tag#L45), since the link handling is done in JavaScript.
