### ISSUE TITLE
Reset Pasword

### ISSUE THREAD

**Issue by unixjeff** [Nordaaker/convos#237]
Is there a process or page im missing on how to reset a users pasword?

**Comment by jhthorsen** [comment]
No, sorry. There's no such thing. We might implement it, if you know of a nice service that allow us to send emails.

**Comment by jhthorsen** [comment]
BTW: Currently, the only way to set a new password is by manully running this command:
```
# 1. Get the old user settings
redis-cli -n 1 hgetall user:YOUR_USERNAME
# 2. Add one line containing the new password to a file 
$EDITOR password.txt
# 3. Encrypt the password and write it to redis
redis-cli -n 1 hset user:YOUR_USERNAME $(perl -nle'chomp;print crypt $_, join "",(".","/",0..9,"A".."Z","a".."z")[rand 64, rand 64]' password.txt)
# 4. Verify that the settings is changed
redis-cli -n 1 hgetall user:YOUR_USERNAME # get the new user settings
```

The reason why I do the extra step by adding the password manually to ```password.txt``` is simply so the password should not be visible in process list.
