### ISSUE TITLE
convos.io ssl cert invalid (wrong host)

### ISSUE THREAD

**Issue by edrex** [Nordaaker/convos#239]
convos.io is being served out of github pages, so the `curl -L https://convos.io/... | bash -` line in the README fails with `curl: (51) SSL: no alternative certificate subject name matches target host name 'convos.by'`

**Comment by marcusramberg** [comment]
I'm assuming you're talking about convos.by the whole time here, and not convos.io?

**Comment by marcusramberg** [comment]
We're actually using cloudflare in front of github, but for some treason cloudflare acceleration was diabled for the root domain, so their https support didn't work. Enabled it now, and will hopefully resolve this as soon as the dns update propagates.

**Comment by marcusramberg** [comment]
Works for me now.
