### ISSUE TITLE
sidebar links broken on android 5/chrome

### ISSUE THREAD

**Issue by edrex** [Nordaaker/convos#240]
On my stock Android 5 device (Moto G Google Play Edition), under Chrome, Convos links of the form `sidebar://foo` _usually_ don't work (sometimes they do). When they don't work, the browser tries to load that URL and returns an error.

This device is a bit low memory for Android 5, so there may be some weirdness due to GC here.

**Comment by jhthorsen** [comment]
I'm not sure if I'm going to be able to fix this without any more details. Could it be that the page is not fully loaded when you click on the links? The JavaScript need to be downloaded and parsed for those links to work. That might take some time if you're cellular connection is flaky.
