### ISSUE TITLE
False positives on mentions.

### ISSUE THREAD

**Issue by ludagoo** [Nordaaker/convos#243]
I keep getting the mention highlight when I am not being mentioned. This also make the safari notifications trigger all the time when I really am not being mentioned.

**Comment by jhthorsen** [comment]
Can you give us an example on when you get mentioned and also what your handle (nick) is?

**Comment by ludagoo** [comment]
![screen shot 2015-04-29 at 7 41 16 am](https://cloud.githubusercontent.com/assets/898064/7391021/2ad0d6fc-ee43-11e4-8abb-4150618e06d0.png)

**Comment by ludagoo** [comment]
my nick is [Lucas] (brackets part of the the nick)

**Comment by ludagoo** [comment]
interesting note: Last night I signed into demo.convos.by and added the same channel to see if it did the same thing on there. I did not but my nick is ludagoo on there. I am starting to wander if it has to do with the brackets. When I /nick [Lucas] convos always complains saying it is not a legit nick but then goes ahead and uses it.

**Comment by ludagoo** [comment]
Wow fast fix. Good job. Thank you for the fast fix! I'm really liking this convos. 

Not same bug but related...

![screen shot 2015-04-29 at 9 56 10 am](https://cloud.githubusercontent.com/assets/898064/7393976/6f943ff0-ee56-11e4-9a01-587d525ae81c.png)

**Comment by marcusramberg** [comment]
Yeah, the regex for matching valid nicks is a bit too naive as well. I've
replaced it with a better one now.

Marcus

**Comment by ludagoo** [comment]
Nice!

**Comment by ludagoo** [comment]
I have put off saying anything because this seems like such an insignificant bug but you'll fixed it so fast before I might as well mention it. 

Now mentions don't work at all with the nick [Lucas]
