### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Xe** [Nordaaker/convos#246]
I am planning on using this for something and want to know if it is dead before I get too deep into things.

**Comment by jhthorsen** [comment]
No, it's not dead, but "master" is not really moving much forward either.

I just blogged about the status here: http://thorsen.pm/perl/2015/08/31/convos-revamped.html

**Comment by jhthorsen** [comment]
We're having a Convos hackathon this Saturday: https://twitter.com/jhthorsen/status/715582472621330433

**Comment by jhthorsen** [comment]
@Xe: The next version is really taking form now:

* https://github.com/Nordaaker/convos/tree/one-point-oh
* https://twitter.com/jhthorsen/status/764532679543062529
