### ISSUE TITLE
No PASS reports since 2015-04-13

### ISSUE THREAD

**Issue by eserte** [Nordaaker/convos#247]
See http://fast-matrix.cpantesters.org/?dist=Convos;reports=1#sl=7,1 for a datetime sorted fail/pass overview. Probably the failures are caused by newer Mojolicious and/or Mojolicious::Plugin::* versions.

**Comment by jhthorsen** [comment]
Convos is no longer on CPAN. Will keep a closer look when we decide to upload it again.
