### ISSUE TITLE
Encrypting logs

### ISSUE THREAD

**Issue by marvelm** [Nordaaker/convos#249]
Is there a way to encrypt the IRC logs so that the operator of an instance of `convos` can't easily read them?

**Comment by jhthorsen** [comment]
No.

I also don't know how that would be possible. Do you know?

We're working on a new version of Convos now, with pluggable backends. Maybe that's something you want to work on? Here is an example of a backend: https://github.com/Nordaaker/convos/blob/batcode/lib/Convos/Core/Backend/File.pm
