### ISSUE TITLE
Environment variable to disable avatars

### ISSUE THREAD

**Issue by socketubs** [Nordaaker/convos#252]
Is it possible?

Thank you! :smile:

**Comment by jhthorsen** [comment]
There are no avatars in the next version we are working on: https://github.com/Nordaaker/convos/blob/batcode/assets/riot/dialog-message.tag

I will do my best to remember this issue _if_ we decide to add avatars in the future.

If you want to contribute/ask questions/shape the next version, you could drop by this Saturday for a Convos hachathon: https://twitter.com/jhthorsen/status/715582472621330433
