### ISSUE TITLE
Websocket mixed-content security error with https reverse proxy

### ISSUE THREAD

**Issue by socketubs** [Nordaaker/convos#253]
I run convos behind an nginx as proxy in `https`.
But websocket tried to connect with `ws://localhost:3000`, then Chrome say this page has mixed-content security error.

I modified `templates/layouts/view.html.ep` to have my website url with an `wss://` prefix. 
Why must I do this? What am I doing wrong?

Thanks!

**Comment by Evlos** [comment]
+1

**Comment by jhthorsen** [comment]
Are you sure you have configured nginx correctly? Maybe you are missing ```proxy_set_header X-Forwarded-Proto $scheme``` ?

https://metacpan.org/pod/distribution/Mojolicious/lib/Mojolicious/Guides/Cookbook.pod#Nginx

**Comment by Evlos** [comment]
@jhthorsen aha, I missed `proxy_set_header X-Forwarded-Proto $scheme`, thanks!

**Comment by jhthorsen** [comment]
Awesome 👍
