### ISSUE TITLE
Digital Ocean how-to in Readme is 404

### ISSUE THREAD

**Issue by ohdns** [Nordaaker/convos#260]
Please update the URL to the digital-ocean how-to.  Thank you!

**Comment by marcusramberg** [comment]
The guide was here - http://thorsen.pm/perl/programming/2014/03/02/convos-on-digitalocean.html but it's been removed from the README in the current version.

**Comment by ohdns** [comment]
Thanks Marcus

**Comment by jhthorsen** [comment]
@ohdns: have you looked at https://convos.by/doc/install.html ? Does it make sense? Do you need more information about how to set up the new version?
