### ISSUE TITLE
Test Convos compatibility with popular IRC networks

### ISSUE THREAD

**Issue by anonsubmitter** [Nordaaker/convos#263]
I think we should test if Convos is compatible with [popular IRC networks](http://irc.netsplit.de/networks/top100.php). Convos has at least had a compability issue with Rizon in the past.
At least EFnet, QuakeNet, IRCnet, Undernet, Snoonet and IRCHighWay should get tested.

**Comment by jhthorsen** [comment]
I hope you can be helpful with this task @anonsubmitter, as discussed on irc://chat.freenode.net:6697/#convos yesterday.

**Comment by anonsubmitter** [comment]
I'll test out the IRC networks mentioned in my previous post once I get Convos updated and configured :)

**Comment by jhthorsen** [comment]
Looking forward to it! Let me know when you have time, and I'll help you set it up. Would be cool if I knew half a day/one day in advance, so I could tweet about it 😄

**Comment by anonsubmitter** [comment]
I have a day off school tomorrow, so maybe then :)

**Comment by jhthorsen** [comment]
Test run:
```
# connecting to chicago.il.us.undernet.org ...
# connecting to efnet.port80.se:6697 ...
# connecting to eris.us.ircnet.net ...
# connecting to irc.irchighway.net:6697 ...
# connecting to irc.perl.org ...
# connecting to irc.snoonet.org:6697 ...
# connecting to underworld1.no.quakenet.org ...

ok 1 - connected to underworld1.no.quakenet.org
ok 2 - connected to irc.perl.org
ok 3 - connected to chicago.il.us.undernet.org
ok 4 - connected to irc.snoonet.org:6697
ok 5 - connected to efnet.port80.se:6697
ok 6 - connected to eris.us.ircnet.net
ok 7 - connected to irc.irchighway.net:6697
1..7
ok
All tests successful.
```
