### ISSUE TITLE
Installation on CentOS7 fails on missing Time::Piece

### ISSUE THREAD

**Issue by denisbr** [Nordaaker/convos#266]
Had to add Time::Piece to the cpanfile to install convos.

```
-------------------------------
All dependencies are installed!

You can now run "./script/convos daemon --listen http://*:8000" to start Convos.

$ ./script/convos daemon --listen http://*:3000
[Mon Aug 22 12:12:36 2016] [info] Generated CONVOS_INVITE_CODE="STRIPPED"
[Mon Aug 22 12:12:36 2016] [warn] Using default (unsafe) session secrets. (Config file was not set up)
Can't locate Time/Piece.pm in @INC (@INC contains: /home/denis/convos-1.0b1/script/../lib /home/denis/convos-1.0b1/script/../local/lib/perl5/x86_64-linux-thread-multi /home/denis/convos-1.0b1/script/../local/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/denis/convos-1.0b1/script/../lib/Convos/Core/Backend/File.pm line 15.
BEGIN failed--compilation aborted at /home/denis/convos-1.0b1/script/../lib/Convos/Core/Backend/File.pm line 15.
Compilation failed in require at (eval 114) line 1.
```

Added the dependency to the ``cpanfile`` and reran install, worked fine after that.

**Comment by jhthorsen** [comment]
Which version of Perl do you have?

**Comment by jhthorsen** [comment]
Maybe there's something odd with Centos:

```
corelist Time::Piece

Data for 2015-12-13
Time::Piece was first released with perl v5.9.5
```

**Comment by jhthorsen** [comment]
Thanks for the bug report! (I'm still curious though)

**Comment by pink-mist** [comment]
Red Hat and its derivatives have a crippled perl by default which only includes the very bare minimum modules for their own things to run. Time::Piece is not one of those things, so instead of being in the ```perl``` package, it's included in the ```perl-core``` one.

**Comment by jhthorsen** [comment]
Oh. How enjoyable 😭 

Thanks for explaining.

heh, on mobile info tells me I'm alone on the channel :/

**Comment by denisbr** [comment]
Sorry for not replying earlier, but yes, @pink-mist explained it very well. Perl packaging in RHEL and any direct descendants is at best weird, at worst broken. Your fix should work very well @jhthorsen 👍

**Comment by jhthorsen** [comment]
Thanks for your contribution @denisbr! Much appreciated 👍
