### ISSUE TITLE
Improve user experience on web

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#269]
There are (at least) these issues regarding the user experience:
- [x] The "info" icon in the top menu is not intuitive. Need som alternative to showing the user list. maybe we should just get back the right side user list?
- [x] The close button looks disconnected from the dialog. Users might click the "x", without realising it closes the current conversation.
- [x] The "unread" count in the main menu (left side) might look like "number of users in the dialog".
- [x] Need an easier way to create a private dialog (other than `/msg`)
- [x] Add timestamp to every message, even if the same person is talking
- [x] Make sure dialog is scrolled to bottom on load
- [x] Reset convos-input height after message is sent

Ideas:
- [x] Maybe we could remove the username/password input fields and rather ask for user/password when the server requires it. It might be confusing to add user/pass, when a lot of the servers doesn't need it.
- [x] Add "close dialog" button inside the dialog list

**Comment by jhthorsen** [comment]
@dotandimet: Anything to add?

**Comment by jhthorsen** [comment]
Convert :P and :/ to emojis.

**Comment by s1037989** [comment]
Both of the ideas on the OP are exactly what I came here to suggest!  Yes!!

The password has always confused me, a novice IRC user.  Do you want my U/P that I just logged into Convos with?  But I just logged in!  :D

**Comment by jhthorsen** [comment]
Closing this since 1a4a487 implements password prompt.
