### ISSUE TITLE
Implement /whowas

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#270]
MagNet (and probably others) allows a `/whowas` command which is exactly like `/whois` but for someone who has left the network. This is especially handy when someone is abusing or when you want to remember details about a contact who is currently offline

**Comment by pink-mist** [comment]
Yes, WHOWAS is part of the original 1459 RFC: https://tools.ietf.org/html/rfc1459#section-4.5.3

So all irc servers should implement it, though some may limit its use.

**Comment by jhthorsen** [comment]
This should probably be implemented in Mojo::IRC and then just proxied from Convos:

* https://github.com/jhthorsen/mojo-irc/blob/master/lib/Mojo/IRC/UA.pm#L257
* https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L185

**Comment by jberger** [comment]
Bump. The lack of this feature made it hard for me to moderate `#mojo`

**Comment by jhthorsen** [comment]
I'm closing this in favour of https://github.com/Nordaaker/convos/issues/317
