### ISSUE TITLE
window.dispatchEvent() on Lumia IE

### ISSUE THREAD

**Issue by mpapec** [Nordaaker/convos#271]
So it seems that `window.dispatchEvent(new Event('resize'));` is responsible for throwing an error.

Related issues:
https://github.com/ftlabs/fastclick/issues/348
https://github.com/tdreyno/morlock.js/issues/5

![wp_ss_20160829_0001](https://cloud.githubusercontent.com/assets/3878347/18062308/915c4b04-6e26-11e6-8deb-f42aacb2a319.jpg)

**Comment by jhthorsen** [comment]
Some more information from the conversation on irc:

window.onerror = function () { alert( JSON.stringify(arguments) ); };
