### ISSUE TITLE
Grouping dialogs. ex: having server, nickserv, chanserv in one common "channel"

### ISSUE THREAD

**Issue by tinaira** [Nordaaker/convos#272]
Are there opportunities to create space for only one server commands that are approved and not all of them have private space.

Could anyone here create just a single tab for "Server" requested commands to be shown and not everything to got thier own tab like "nickserv" "chanserv" etc... regards

**Comment by jhthorsen** [comment]
I do like this idea, but there's one problem that needs to be solved: how do you know who you're talking to, if the conversations are grouped..? You would have to prefix all the messages with `/cs`, `/ns` or `/msg` right..? I'm curious if that is very user friendly or not.

What do you think @marcusramberg ?

**Comment by marcusramberg** [comment]
Not sure how this would work... i think the command line clients like irssi  do it with a -server flag or similar?

**Comment by jhthorsen** [comment]
I don't understand. Where is the "-server" flag set? On the dialog..? Command line..?

**Comment by tinaira** [comment]
It simply shows NICKSERV nickname for nickserv but not a personal space it's like there is an window where does show all SERVER stuff going on

**Comment by jhthorsen** [comment]
@tinaira: I was thinking about how to reply to the correct *person* in such a group chat.

**Comment by tinaira** [comment]
@jhthorsen well that's works to where NickServ, ChanServ, HostServ, BotServ to be on single group

**Comment by Grinnz** [comment]
Note that these nicks are *services*, not server functions. They are distinct from server commands like /PRIVMSG and /WHOIS, though some servers implement /NS to forward messages to NickServ for instance. I don't agree with grouping their messages, though some clients will group notices (not messages) which some of these services use.

**Comment by jhthorsen** [comment]
@Grinnz: My plan now, is to implement this as either an optional plugin or a generic thing, where you can group "whatever is in the left side conversation menu".

**Comment by jhthorsen** [comment]
Closing this now, since there seem very little interest in the issue.

**Comment by SvetlanaTkachenko** [comment]
I think this can be resolved by sending all private notices to the 'irc-freenode' chat view. I would be highly interested.

**Comment by Wikiwide** [comment]
I think that there should be an option to group different channels/chats, by user, for whatever purpose they prefer. For example, I would have grouped irc-freenode, freenode-connect, NickServ, ChanServ and SaslServ in "Zubbish" group (to send them to the end of the list, since sorting is alphabetical). I understand that keeping user interface compact and intuitive will be difficult, but having all these Services pop up again and again, polluting my screen space, just because I had to reconnect to server/channel yet again... It's exhausting.

**Comment by SvetlanaTkachenko** [comment]
I think a possible workaround for this is a /close command which accepts a channel name as an argument. Now in freenode view I typed '/close nickserv' and it closed the freenode view itself. So sad. :-1:
