### ISSUE TITLE
Placeholder: Improve / add missing information to https://convos.by

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#274]
- [x] Add https://convos.by/doc/faq.html
  - Include note about `nohup script/convos daemon &`
  - document MOJO_REVERSE_PROXY

**Comment by tinaira** [comment]
Yeah good idea that's helped me out keeping process alive at all time :), and should be as a faq to users that don't know how to do it.

**Comment by jhthorsen** [comment]
Closed by e096af1.

Will re-open if there are other things that should be done.
