### ISSUE TITLE
The user doesn't appear after changing their Nicknames

### ISSUE THREAD

**Issue by tinaira** [Nordaaker/convos#276]
When someone changes their nicknames on any specific channel he doesn't appear to the Participants anymore, Image example http://i.imgur.com/DH5XRIf.png.

**Comment by jhthorsen** [comment]
That's awful 😞  I also noticed that when people quit IRC, it is not noticed in the frontend.

Looking at this now.

**Comment by jhthorsen** [comment]
Pretty sure this is fixed now. Let me know if it doesn't work as expected.

**Comment by tinaira** [comment]
Thank you that issue has been fixed indeed, but please check issue #277
