### ISSUE TITLE
Youtube video is aligned to the right of the posted link

### ISSUE THREAD

**Issue by mpapec** [Nordaaker/convos#279]
This looks awkward a bit on the desktop.

![image](https://cloud.githubusercontent.com/assets/3878347/18473454/4b80b208-79bd-11e6-838d-5e0794878560.png)

**Comment by jhthorsen** [comment]
In which browser is this? For me, the movies (and other embed information) are always rendered under the link.

Are you running master or stable? Have you done any changes locally?

**Comment by jhthorsen** [comment]
Oh! Nevermind... saw it myself now.

Thanks for the bug report.
