### ISSUE TITLE
Figure out a way to handle "mIRC colors"

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#281]
The IRC message below looks like `[13mojolicious-plugin-openapi] 15jhthorsen pushed 1 new commit to 06master: 02https://git.io/viMfT`:

```
:swag!~swag@192.30.252.45 PRIVMSG #swagger :[^C13mojolicious-plugin-openapi^O] ^C15jhthorsen^O pushed ^B1^O new commit to ^C06master^O: ^C02^_https://git.io/viMfT^O
```

I'm not sure if we should handle colours (?), but we should handle the characters somehow.

**Comment by marcusramberg** [comment]
i believe we were stripping colors in the previous version, that seems like the way to go to me.

**Comment by jhthorsen** [comment]
Yeah. Seems like a clean and simple solution to me as well. So no _bold_ or something like that?

**Comment by jhthorsen** [comment]
Discussed it with @marcusramberg and decided to strip colours on input.
