### ISSUE TITLE
window.dispatchEvent not supported on Lumia

### ISSUE THREAD

**Issue by mpapec** [Nordaaker/convos#282]
It dies on `document.dispatchEvent(new CustomEvent("beforeConvosStart",{detail:detail}));`

The error looks similar to https://github.com/Nordaaker/convos/issues/271

**Comment by jhthorsen** [comment]
Could you provide more details about the actual browser, so I can figure out if I can polyfill the missing pieces?

**Comment by jhthorsen** [comment]
Could it be that it fails on `new CustomEvent` instead of `document.dispatchEvent`?

**Comment by mpapec** [comment]
Good point; it might be even that both `CustomEvent` and `dispatchEvent` are not supported.

Browser info:
https://www.whatismybrowser.com/w/2LTMGJX

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by jhthorsen** [comment]
Hope this does the trick.
