### ISSUE TITLE
Build Ubuntu snappy app installer (self contained)

### ISSUE THREAD

**Issue by senorsmile** [Nordaaker/convos#285]
I just listened to your convo on CMOS, and thought we should create an issue so we don't forget about this: 

http://code-maven.com/cmos-16-jan-henning-thorsen-and-marcus-ramberg

Ubuntu snappy apps are self contained installable programs that just work!  They are initially supporting Ubuntu, but are working with the community to support practically every other Linux distribution as well!

Docs: http://snapcraft.io/docs/build-snaps/

**Comment by jhthorsen** [comment]
"Snappy"! I totally forgot the name of the packages during the interview. Thank you!

I'm planning to build packages, some time early next year.

**Comment by jhthorsen** [comment]
Other things to consider:

- [ ] Docker https://github.com/Nordaaker/convos/blob/master/Dockerfile - https://www.howtoforge.com/tutorial/building-and-publishing-custom-docker-images/ -https://gist.github.com/mpapec/edd39fe639bb6ecd862710260c78ca90
- [ ] Heroku - https://github.com/Nordaaker/convos/blob/06ce418d221c361dc95ef874ad43c61cc5ed540d/app.json
- [ ] http://flatpak.org/

**Comment by jhthorsen** [comment]
Released to the ubuntu store now. Can you try to install it @senorsmile? https://myapps.developer.ubuntu.com/dev/click-apps/7312/

**Comment by jhthorsen** [comment]
I can't see Convos in https://uappexplorer.com/apps?type=snappy

Maybe it's because I only did a release candidate?

**Comment by jhthorsen** [comment]
It's now visible: https://uappexplorer.com/app/convos.jhthorsen
