### ISSUE TITLE
Text can not be read

### ISSUE THREAD

**Issue by kberov** [Nordaaker/convos#286]
I went to http://demo.convos.by/ registered and could not continue.
I only see several text slapped one over each other.
![convos-bad-texts](https://cloud.githubusercontent.com/assets/111614/19416064/c9137812-9386-11e6-96ef-b8478f9f91b0.png)

This happens on Ubuntu 16.04 Firefox 49.

**Comment by jhthorsen** [comment]
Oh! That's just awful. I will download and test in Firefox some time later this week.

**Comment by jhthorsen** [comment]
Sorry, but I'm unable to reproduce this bug. Looks fine to me.
