### ISSUE TITLE
& and % user modes in channels not recognized

### ISSUE THREAD

**Issue by Grinnz** [Nordaaker/convos#287]
If a user has & (+a, admin) or % (+h, halfop) status in a channel, the symbol is not removed from their name so trying to get the user's info or PM them does not work correctly. The ~ (+q, owner) status is removed correctly but is displayed as ~ and not consistent with the +o and +v statuses.

**Comment by pink-mist** [comment]
Please note that different networks use different sigils and letters for different statuses.

I've also, in addition to ```&``` for ```+a``` seen ```!``` for ```+a``` and ```&``` for ```+q```, which I believe is called ```owner``` on the network I've seen that ... ```%``` seems relatively universal for ```+h``` though.

**Comment by pink-mist** [comment]
There's a modeline when you connect to a network that lists the letters and sigils the network uses

**Comment by pink-mist** [comment]
For example, my own testing server sends this:
```
[localhost:6667] >>> :localhost 005 pink_mist CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CDEFGJKLMOPQTcdgimnpstuz CHANLIMIT=#:50 PREFIX=(aohv)!@%+ MAXLIST=bqeI:100 MODES=5 NETWORK=Channel0 KNOCK STATUSMSG=@+ CALLERID=g :are supported by this server
[localhost:6667] >>> :localhost 005 pink_mist CASEMAPPING=rfc1459 NICKLEN=31 CHANNELLEN=50 TOPICLEN=390 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=100 FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:8,NOTICE:8,ACCEPT:,MONITOR: WHOX :are supported by this server
[localhost:6667] >>> :localhost 005 pink_mist CLIENTVER=3.0 SAFELIST ELIST=CTU :are supported by this server
```

Where the important bit as far as this bug is concerned is the ```PREFIX=(aohv)!@%+```

**Comment by jhthorsen** [comment]
I think the two commits above should fix this. Do you have any further input? Let's re-open if you do.

I will make a new release of Mojo::IRC and convos later today or tomorrow.

**Comment by pink-mist** [comment]
Well, first of all, you completely missed ```!```, and second of all, hardcoding them will lead to other bugs if the irc network allows any such character in nicks (which I guess isn't standards compliant, but I know there are IRC servers out there that does this anyway). You really should be getting them from the PREFIX setting of the 005 message.

**Comment by jhthorsen** [comment]
What do you think about https://github.com/jhthorsen/mojo-irc/commit/568f7895c1d588afc53be5a064bedc8af05259f6 ?

**Comment by jhthorsen** [comment]
Closing this now after releasing Mojo::IRC 0.42.
