### ISSUE TITLE
email addresses with '.' generate invalid usernames

### ISSUE THREAD

**Issue by dearieme** [Nordaaker/convos#296]
If I register an account with a dot in the name part of the email address, e.g. 'foo.bar@example.com' then attempt join a channel you get an invalid username error from the server.

The server is ngircd. I coudn't find anything about the username format in the RFC but from the looks of [the ngircd commit](https://arthur.barton.de/cgi-bin/gitweb.cgi?p=ngircd.git&a=commit;h=6680b536c4da7dc27e11490fe098e98cb0393fa2) other servers may behave similarly.

I'm not sure of the implications, but perhaps just strip non-alpha chars when generating the username?

[Edit: fixed the commit link]

**Comment by jhthorsen** [comment]
Sounds good to me! I didn't know this was an issue, but I don't see any harm on removing "." as well. Do you think removing it, or replacing it with "_" is the best choice?

**Comment by dearieme** [comment]
I think remove, ngircd only allows alphanumeric (see commit - sorry fixed the link!) It's not really a UI thing, it appears in the output of /userhost and friends but I don't think the format would matter to anything trying to use it programatically like bots.

**Comment by jhthorsen** [comment]
This fix will be part of the next release of Convos, 0.99_18. Hope to make a release later or early next week.

**Comment by jhthorsen** [comment]
I do think it's weird that the server don't allow "_" in the nick though... What should the logic for duplicate nicks be like then? Right now, if "yournick" is taken, then Convos will automatically try to add "_" at the end, so the nick will become "yournick_".

**Comment by dearieme** [comment]
Ah it's the username when initiating the connection that has the issue - not the nick. It looks like it is generated in Convos::Core::Connection line 90. Apologies for confusion.

**Comment by dearieme** [comment]
p.s. I've introduced Convos to our mainly Perl dev team where it has been warmly received, we'll almost certainly be setting up a Convos dev environment and hopefully contributing!

**Comment by jhthorsen** [comment]
Ah! That makes perfect sense 😄 

I should've read the bug report more closely.

**Comment by jhthorsen** [comment]
Hope I fixed the correct thing this time! 😃
