### ISSUE TITLE
Notifications bar encoding issue

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#297]
I saw this today, clearly something is being encoded or decoded too many times or not enough someplace. See neilb's "while ..."
<img width="1211" alt="screen shot 2016-11-17 at 10 25 57 am" src="https://cloud.githubusercontent.com/assets/735765/20399524/f739e93a-acb6-11e6-9b97-a71ac1c95f22.png">

**Comment by jhthorsen** [comment]
Hard to figure this out without sample data from notifications.log and a conversation log. Can you provide that @jberger? Please url_encode the data or something before pasting it into this thread, to make sure we don't miss out on anything.

**Comment by jhthorsen** [comment]
Closing this because I cannot figure it out without further information.
