### ISSUE TITLE
Replies from Chanserv aren't echoed

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#298]
I don't know if it is because they arrive too fast or if they are being read in some other way but when I message Chanserv, for example, `/msg Chanserv help` I don't get any response, but it does show up when I refresh the page.

**Comment by jhthorsen** [comment]
I'm pretty sure they are, but under your nickname in the main menu. I guess you've closed the "Chanserv" dialog before sending "/msg Chanserv help"?

I'm looking into this now.
