### ISSUE TITLE
Echo /mode +b messages

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#299]
I was trying to moderate in `#mojo` and I was unable to see if/when I had successfully banned a user. There was no output from sending the op +b command.

Addtionally, it might be useful to have some kind of moderation tools to help craft the ban command.

**Comment by jhthorsen** [comment]
Not sure what "moderation tools" is, but first impression is that this is too low level for convos. I could be wrong.

**Comment by jhthorsen** [comment]
I wonder if this is fixed in master now.

Please re-open if it is not.
