### ISSUE TITLE
upgrade from older version

### ISSUE THREAD

**Issue by unixjeff** [Nordaaker/convos#304]
Is there a process to upgrade from an older version?

**Comment by jhthorsen** [comment]
Yes, just run the installation script again.

https://convos.by/doc/getting-started.html#quick-start-guide

Going to keep this task open until I have documented this in either https://github.com/Nordaaker/convos/blob/gh-pages/doc/getting-started.md or https://github.com/Nordaaker/convos/blob/gh-pages/doc/faq.md

Where would you document it @unixjeff ?
