### ISSUE TITLE
Ordered Participants list

### ISSUE THREAD

**Issue by oliwer** [Nordaaker/convos#308]
The list of participants should be ordered alphabetically.

**Comment by jhthorsen** [comment]
It already is...?

https://github.com/Nordaaker/convos/blob/master/assets/vue/convos-dialog-settings.vue#L48

**Comment by oliwer** [comment]
This bug is actually linked with #303. When I type `/names` the list gets populated but unordered.

But yes, the list is ordered in the normal case.
