### ISSUE TITLE
Push-notifications Android/Firefox/iOS

### ISSUE THREAD

**Issue by ekianjo** [Nordaaker/convos#312]
I have notifications "on" but I dont seem to get system-wide notifications on Firefox on Android. Is there something else I should be doing ?

**Comment by ekianjo** [comment]
Of course please let me know in case you need Android version + exact Firefox version + exact Convos version... my convos build is recent though (a week ago) and FIrefox is up to date.

**Comment by jhthorsen** [comment]
Might want to look at https://pushover.net/ as well.

**Comment by jhthorsen** [comment]
Going to put this issue in the fridge, but keep #493 open.

**Comment by jhthorsen** [comment]
Moving this issue into the backlog, since #597 was created
