### ISSUE TITLE
Add support for different color themes

### ISSUE THREAD

**Issue by ekianjo** [Nordaaker/convos#313]
I know this is probably just a css settings away, but it would be great to have a few choices in terms of UI colors/themes. The default white/green looks nice, but it's not easy on the eyes (I would like to have a dark theme if possible). Happy to help if needed.

**Comment by jhthorsen** [comment]
I do not have time/interest to create new colour themes, but I will keep this issue open until I've created a blog post about how to customise Convos. I can try to explain it here first:

1. Figure out what `$CONVOS_HOME` is. The default location is `$HOME/.local/share/convos/`.
2. If you want to override the settings in _variables.scss, You can do that by creating this file: `$HOME/.local/share/convos/assets/sass/_variables.scss`
3. If you want to override styling, using CSS rules, you can do that by creating the file `$HOME/.local/share/convos/assets/sass/_custom.scss`

Please have a look at the files below to see what that can go into `_variables.scss`:
* http://materializecss.com/
* https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss
* https://github.com/Nordaaker/convos/blob/master/assets/sass/_variables.scss

And here is an example `_custom.scss` file for floating nicks on the left side of the messages:
```
.convos-message .title {
  padding-right: 4px;
  float: left;
  min-width: 7em;
  display: block;
}
 
.convos-message.same-user .title {
  display: block !important;
}
```

If you have created either of the files above, you should see something like this in the log output:

```
[info] Loading custom asset: /home/odc/.convos/assets/sass/_variables.scss
[info] Loading custom asset: /home/odc/.convos/assets/sass/_custom.scss
```

Also note that making too many specific changes in `_custom.scss` might break in the future, while just changing colours in `_variables.scss` is much safer.

I've tried to add useful variables to `_variables.scss`, but I know there are probably more variables to be added to support a dark theme.

I would very much like to take a PR of a dark theme, but I have no plans to implement it myself.

**Comment by ekianjo** [comment]
thanks, I will probably make a PR on this matter then for the scss part. 
How about making it into a menu in the profile, can you take that on once several themes are available?

**Comment by jhthorsen** [comment]
It kind of makes sense to put it into the profile, but I need to 1) Check if we think the theme is of our liking 2) Need to see if we really want this customisation.

Going to discuss it with @marcusramberg, once the PR is open.

**Comment by jhthorsen** [comment]
One of the big issues by adding themes is that we also need to maintain those themes... One hack to make it all work could be to add classname to `<body>´ (something like "theme-darker"), and then allow customisation in `_custom.scss` like this:

```
body.theme-darker {
  background-color: #222;
  color: #999;
}
```

That way it could be community driven and I wouldn't have to maintain it all.

**Comment by V3XATI0N** [comment]
I've tried to create custom CSS rules, but every time it gets to parsing _custom.scss, it crashes with

`Mojolicious::Plugin::AssetPack::Pipe::Sass requires ruby. https://ruby-lang.org/en/documentation/installation`

I thought it was because I am terrible at SASS, but it happens no matter how simple the instructions are, and also if I edit values in any of the existing scss files as well. Obviously I'm doing something wrong, but what?

**Comment by jhthorsen** [comment]
That's because sass require a processor. Either the perl library CSS::Sass or the executable `sass` or `sassc`.

You can try installing the perl library using `cpanm CSS::Sass` or `./script/convos install --develop`. If that doesn't work, then you need to install the binary, which require Ruby: http://sass-lang.com/install

**Comment by V3XATI0N** [comment]
here is the complete _custom.scss I use on mine. posting here mainly for the heck of it. Would be cool to have a separate repo or subfolder or something for people to submit their themes to the project.

`//colors
$color_luxor_gold_approx: #a17a33;
$color_hemlock_approx: #57553c;
$color_limed_ash_approx: #718062;
$color_rangoon_green_approx: #191716;
$color_karry_approx: #ffe7cf;
$color_lynch_approx: #65788f;
$color_sea_mist_approx: #c1e2c2;
$white: #fff;
$color_alto_approx: #ddd;
$color_tapa_approx: #757575;
$color_star_dust_approx: #9f9f9f;
$color_gallery_approx: #eee;
$color_dune_approx: #383332;
$color_moss_green_approx: #a5d5a7;
$color_mako_approx: #43454f;
$color_indian_khaki_approx: #c8b491;
$color_potters_clay_approx: #845336;
$color_barley_corn_approx: #a18b62;
$color_woodsmoke_approx: #0f0e0d;
$color_sweet_corn_approx: #f7ea94;
$black:  black;

//fonts
$font_0: Segoe UI;
$font_1: Roboto;
$font_2: Oxygen;
$font_3: Ubuntu;
$font_4: Cantarell;
$font_5: Fira Sans;
$font_6: Droid Sans;
$font_7: Helvetica Neue;
$font_8: ubuntu mono;
$font_9: consolas;
$font_10: monospace;

//@extend-elements
//original selectors
//header h2, header a, header .material-icons, header .link-embedder.text-paste .paste-meta::before, .link-embedder.text-paste header .paste-meta::before
%extend_1 {
	color: $color_indian_khaki_approx;
	display: inline-block;
	font-size: 2rem;
	height: 56px;
	line-height: 56px;
}


a {
	color: $color_luxor_gold_approx;
}
.divider {
	background-color: $color_hemlock_approx;
}
blockquote {
	border-left: 5px solid $color_limed_ash_approx;
}
table {
	&.borde#A18B62 {
		> thead > tr {
			border-bottom: 1px solid $color_hemlock_approx;
		}
		> tbody > tr {
			border-bottom: 1px solid $color_hemlock_approx;
		}
	}
	&.striped > tbody > tr:nth-child(odd) {
		background-color: $color_rangoon_green_approx;
	}
	&.highlight > tbody > tr:hover {
		background-color: $color_rangoon_green_approx;
	}
}
thead {
	border-bottom: 1px solid $color_hemlock_approx;
}
.collection {
	border: 1px solid $color_karry_approx;
	.collection-item {
		background-color: $color_rangoon_green_approx;
		border-bottom: 1px solid $color_karry_approx;
		&.active {
			background-color: $color_lynch_approx;
			color: $color_sea_mist_approx;
			.secondary-content {
				color: $white;
			}
		}
	}
	a.collection-item {
		display: block;
		//Instead of the line below you could use @include transition($transition-1, $transition-2, $transition-3, $transition-4, $transition-5, $transition-6, $transition-7, $transition-8, $transition-9, $transition-10)
		transition: .25s;
		color: $color_lynch_approx;
		&:not(.active):hover {
			background-color: $color_alto_approx;
		}
	}
	&.with-header .collection-header {
		background-color: $color_rangoon_green_approx;
		border-bottom: 1px solid $color_karry_approx;
		padding: 10px 20px;
	}
}
.secondary-content {
	color: $color_lynch_approx;
}
.progress {
	background-color: $color_lynch_approx;
	.indeterminate {
		background-color: $color_lynch_approx;
	}
}
.btn-floating {
	background-color: $color_lynch_approx;
	&:disabled {
		background-color: $color_hemlock_approx !important;
		//Instead of the line below you could use @include box-shadow($shadow-1, $shadow-2, $shadow-3, $shadow-4, $shadow-5, $shadow-6, $shadow-7, $shadow-8, $shadow-9, $shadow-10)
		box-shadow: none;
		color: $color_star_dust_approx !important;
		cursor: default;
		&:hover {
			background-color: $color_hemlock_approx !important;
			color: $color_star_dust_approx !important;
		}
	}
	&:hover {
		background-color: $color_limed_ash_approx;
	}
}
.btn {
	color: $white;
	background-color: $color_lynch_approx;
	&:hover {
		background-color: $color_lynch_approx;
	}
}
.btn-large {
	color: $white;
	background-color: $color_lynch_approx;
	&:hover {
		background-color: $color_lynch_approx;
	}
}
.btn-delete {
	color: $white;
	background-color: $color_lynch_approx;
	&:hover {
		background-color: $color_lynch_approx;
	}
}
.dropdown-content {
	background-color: $color_rangoon_green_approx;
	li {
		&:hover {
			background-color: $color_gallery_approx;
		}
		&.active {
			background-color: $color_gallery_approx;
			&.selected {
				background-color: $color_dune_approx;
			}
		}
		&.selected {
			background-color: $color_gallery_approx;
		}
	}
}
header {
	background-color: $color_limed_ash_approx;
	text-align: right;
	height: 56px;
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	z-index: 900;
	h2 {
		float: left;
		margin: 0;
		@extend %extend_1;
	}
	a {
		@extend %extend_1;
	}
	.material-icons {
		@extend %extend_1;
	}
	.link-embedder.text-paste .paste-meta::before {
		@extend %extend_1;
	}
}
.convos-header-links {
	background: $color_woodsmoke_approx !important;
}
.convos-dialog-container {
	font-family: $font_0, $font_1, $font_2, $font_3, $font_4, $font_5, $font_6, $font_7, $font_8, $font_9, $font_10;
	background: $color_gallery_approx;
}
.message {
	margin-top: 3px;
}
.convos-message {
	//Instead of the line below you could use @include border-radius($radius, $vertical-radius)
	border-radius: 2px;
	border: 1px solid $color_gallery_approx !important;
	//Instead of the line below you could use @include box-shadow($shadow-1, $shadow-2, $shadow-3, $shadow-4, $shadow-5, $shadow-6, $shadow-7, $shadow-8, $shadow-9, $shadow-10)
	box-shadow: none;
	padding: 4px;
	margin: 4px;
	background: $white;
	.title {
		background-color: $color_mako_approx !important;
		color: $white !important;
		padding: 2px;
		padding-left: 4px;
		padding-right: 4px;
		border-radius: 3px;
	}
	&.highlight .message {
		background: $color_sweet_corn_approx;
		margin-left: 2px;
	}
}
footer.page-footer {
	background-color: $color_rangoon_green_approx;
	.footer-copyright {
		background-color: $color_rangoon_green_approx;
	}
}
span.badge {
	color: $color_tapa_approx;
	&.new {
		color: $white;
		background-color: $color_lynch_approx;
	}
}
select:focus {
	outline: 1px solid $color_moss_green_approx;
}
button:focus {
	outline: none;
	background-color: $color_mako_approx;
}
.link-embedder.text-paste {
	header .paste-meta::before {
		@extend %extend_1;
	}
	div.link .paste-meta::before {
		color: $color_barley_corn_approx !important;
	}
}
body.notouch {
	header a:hover {
		background: $color_lynch_approx;
	}
	.convos-main-menu .link.dialog:hover .close:hover {
		background-color: $color_potters_clay_approx;
	}
}
div.link {
	.material-icons {
		color: $color_barley_corn_approx !important;
	}
	.simple {
		color: $color_barley_corn_approx !important;
	}
	span.name {
		color: $color_barley_corn_approx !important;
	}
	.link-embedder.text-paste .paste-meta::before {
		color: $color_barley_corn_approx !important;
	}
}
`

**Comment by jhthorsen** [comment]
Some questions/comments:

* Where is the `table`, `thead`, `.progress`, and `footer.page-footer` styling in use?
* You might be interested in `$font-family-default` and `$font-family-monospace` that I added to Convos 0.99_31
* Why don't you use a custom `_variables.scss` file to override the colours?
* Why do you use `body.notouch` instead of just `body`?

**Comment by V3XATI0N** [comment]
Honestly this theme is a collaboration and most of it comes from a friend of mine. I assume some of it is boilerplate lifted from somewhere else (hence the footer and body tags). As to why I didn't use _variables.scss, I wanted to control everything in a single file rather than have to edit 2 or 3 files to make one change.

**Comment by jhthorsen** [comment]
The reason why you want _variables.scss is that you can then just change variables that the existing sass files already use. You're in no way control that ".convos-message" will be named ".convos-message" in the next release, but you can be very certain (at least a lot more sure) that the variable names in https://github.com/Nordaaker/convos/blob/master/assets/sass/_variables.scss won't change. You have even more variables to play with here: https://github.com/Dogfalo/materialize/blob/master/sass/components/_variables.scss

**Comment by V3XATI0N** [comment]
Thanks, I'll take that into consideration. There are some attributes that are not handled in variables so I'll still need a separate _custom.scss no matter what, though.

**Comment by jhthorsen** [comment]
Please tell me which, so we can define variables for them. My goal is to make new layouts with just _variables.scss

**Comment by V3XATI0N** [comment]
I added background, border-radius, and padding to `.convos-message .title` and `.convos-message .message`, changed the bgcolor of the `.highlight` messages, and generally altered padding and margin on a bunch of different elements.

**Comment by jhthorsen** [comment]
Dark mode will be part of version 1.01.

https://github.com/Nordaaker/convos/milestone/9
