### ISSUE TITLE
IRC commands not being passed to server

### ISSUE THREAD

**Issue by OvermindDL1** [Nordaaker/convos#317]
Attempting to use `/away <msg>` and `/back` does nothing but give this message:
```
/away blahg: Unknown IRC command.
```
Which is odd because the server most definitely does support this command.  Tested a few others commands and none of those worked either.

**Comment by jhthorsen** [comment]
This used to be a design decision, since I wanted to track responses to given commands, while the IRC protocol doesn't really work that way.

I'm working on a new branch https://github.com/Nordaaker/convos/tree/message-event which will allow you to send/receive any command.

**Comment by OvermindDL1** [comment]
Awesome, yeah a *lot* of the IRC commands this server basically requires were not working...  ^.^
