### ISSUE TITLE
Perl Error After Upgrading System Libraries

### ISSUE THREAD

**Issue by ekianjo** [Nordaaker/convos#319]
I am at loss to identify where this issue is coming from - Convos refuses to start after a server update and reboot. The error I get is 

> perl: symbol lookup error: mypathhere/convos/script/../local/lib/perl5/arm-linux-gnueabihf-thread-multi-64int/auto/Crypt/Eksblowfish/Eksblowfish.so: undefined symbol: Perl_xs_apiversion_bootcheck

Any idea what I can do to fix it ?

**Comment by jhthorsen** [comment]
Hi, I think probably your perl version was changed after update? If so, I would just nuke the installed packages and do a fresh install. Something like this:

```
cd /path/to/convos
rm -rf local/{bin,lib,man}
./script/convos install
```

**Comment by jhthorsen** [comment]
Please report back if it worked, and I will add it to https://convos.by/doc/faq.html

**Comment by pink-mist** [comment]
Another thing that could be useful to read for an issue like this: https://bbs.archlinux.org/viewtopic.php?pid=1428675

That thread describes what's going on in Arch and its derivatives, but it's certainly something that could happen on other distributions as well if you install things from CPAN, and the advice given there could be somewhat applied generally.

**Comment by ekianjo** [comment]
I tried your first method above, and reinstalling dependencies failed at File-HomeDir-1.00
I checked the debug file and it complains about this:

> Can't locate inc/Module/Install.pm

and this causes the Makefile to fail.

**Comment by ekianjo** [comment]
I managed to overcome this issue by installing that module:

sudo apt-get install libmodule-install-perl

Did not have to install it in my previous convos install though.

**Comment by ekianjo** [comment]
I was able to get to the end of the install. Problem fixed, thank you. You may want to add this kind of things in the FAQ if it happens to anyone else.

**Comment by jhthorsen** [comment]
Keeping this open until I've documented it on the website.
