### ISSUE TITLE
First shown channel shows all users inactive

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#321]
When I load convos some channel is already active (say #mojo for example). After a few seconds all user names strike out and all text becomes grayed so as to show all users are inactive (though clearly this isn't true). When I switch channels all the others behave correctly but when I go back to that first channel (#mojo again) the users/text are still shown as inactive.

I can mitigate by clicking a channel I rarely use and reloading. This doesn't fix the problem but isolates it someplace I don't usually check.

**Comment by jberger** [comment]
I was hoping that `/names` would help kick it into action but instead was told I was the only participant. I'm including a screenshot from immediately after calling `/names`.
![screen shot 2017-01-30 at 1 08 45 pm](https://cloud.githubusercontent.com/assets/735765/22437356/611d2f36-e6ed-11e6-8b4a-fe65f130f204.png)

**Comment by jhthorsen** [comment]
I don't know how to reproduce. Can you give me some output from either the console or when running with MOJO_IRC_DEBUG=1 and CONVOS_DEBUG=1 ?

**Comment by marcusramberg** [comment]
I've also seen this issue or something similar, when I join a new channel on #freenode from beta.convos.by, at first it updates the user list to show all the members, but then after a few seconds the list clears and it shows 0 participants. Just tested this by joining #linux - You can see that new users are tracked as they join tho:

![image](https://cloud.githubusercontent.com/assets/5526/22498710/51e88dda-e85a-11e6-9204-3e9970e59b38.png)

**Comment by jhthorsen** [comment]
Pretty sure this is fixed now. Going to test it before making a new release.

Thanks for reporting in ❤️

**Comment by jberger** [comment]
Ooooh thanks! I'm going to upgrade right away!
