### ISSUE TITLE
custom config file not working

### ISSUE THREAD

**Issue by saitoh183** [Nordaaker/convos#322]
Im trying to use the custom config file but i dont know what im doing wrong:

i tried json:

```
{
  "backend":            "Convos::Core::Backend::File",
  "forced_irc_server":  "irc.freenode.net",
  "invite_code":        "0okmju7",
  "plugins":            {},
  "secure_cookies":     1,
  "session_secrets":    ["q4@sx#z!Vj5y,*tYB7B&G#wt!,2na#G6*egRDN"]
}
```

and Perl:

```
{
  forced_irc_server =>  'chat.freenode.net:6697',
  invite_code =>        '0okmju7',
  secure_cookies =>     1,
  session_secrets =>    ['q4@sx#z!Vj5y']
}
```
when i start convos, i see 
`[warn] Using default (unsafe) session secrets. (Config file was not set up)`

what am i doing wrong?

**Comment by jhthorsen** [comment]
It looks right... https://github.com/Nordaaker/convos/blob/master/t/data/config.json

Did you set the MOJO_CONFIG environment variable? https://convos.by/doc/config.html#mojoconfig

**Comment by saitoh183** [comment]
no i didnt...i should put it in etc/environment?

**Comment by jhthorsen** [comment]
Out of curiosity: Where did you put the config file? I would like to know, since maybe Convos should look for the config file in that location by default.

Not not put it in `etc/environment`.

I do something like this:

```
#!/bin/sh

export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin";
export CONVOS_HOME=/var/data/convos
export CONVOS_SECRETS=xxxxx

exec /usr/bin/sudo -E -u www-data perl ./script/convos daemon --listen http://*:8002 2>>/var/log/convos.log 1>>/var/log/convos.log
```

But if you want a config file, then you can do this instead:

```
#!/bin/sh

export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin";
export MOJO_CONFIG=/path/to/convos-config.json

exec /usr/bin/sudo -E -u www-data perl ./script/convos daemon --listen http://*:8002 2>>/var/log/convos.log 1>>/var/log/convos.log
```

How do you start Convos?

**Comment by saitoh183** [comment]
I start convo with Supervisor

```
[program:Convos]
command=/home/saitoh183/convos/script/convos /home/saitoh183/.local/share/convos/convos.conf daemon --listen http://*:8082
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/convos.err.log
stdout_logfile=/var/log/supervisor/convos.out.log
user=saitoh183
environment=MOJO_REVERSE_PROXY=1
```

**Comment by jhthorsen** [comment]
Ah! I totally forgot about that way of starting Convos 🙈 

So this should work: (I just tested it)

```
command=/home/saitoh183/convos/script/convos /home/saitoh183/.local/share/convos/convos.conf --listen http://*:8082
```

Could you point me where you read about the extra "daemon" argument, so I can fix the documentation?

Also, are you sure that the user running the process has access to the file at startup time?

**Comment by jhthorsen** [comment]
Putting convos.conf or convos.json in `CONVOS_HOME` is a good idea! I will make Convos look for the config file there by default.

**Comment by saitoh183** [comment]
For the extra daemon i didnt see it in the documentation when using MOJO_REVERSE_PROXY=1 but it was there for 

# Listen on all IPv4 interfaces
$ ./script/convos daemon --listen http://*:8080

and other listen methods. I just added it by accident and it was working but not the config. So i would need to remove daemon?

**Comment by saitoh183** [comment]
MOJO_REVERSE_PROXY=1 is needed in the command because i need reverse proxy

**Comment by saitoh183** [comment]
running 
`MOJO_REVERSE_PROXY=1 /home/saitoh183/convos/script/convos /home/saitoh183/.local/share/convos/convos.conf --listen http://*:8082`

or

`/home/saitoh183/convos/script/convos /home/saitoh183/.local/share/convos/convos.conf --listen http://*:8082`

i still get 

```
[Mon Feb 27 11:27:54 2017] [info] Generated CONVOS_INVITE_CODE="e032b748e4c51b15b67806e3aebe6f0e"
[Mon Feb 27 11:27:54 2017] [warn] Using default (unsafe) session secrets. (Config file was not set up)
```

**Comment by jhthorsen** [comment]
There was a bug which is fixed in 1667d3d. I will make a new release later this week or you can try out master.

In the meanwhile, you need to set the `CONVOS_INVITE_CODE` variable, like this:

```
CONVOS_INVITE_CODE="0okmju7" MOJO_REVERSE_PROXY=1 /home/saitoh183/convos/script/convos /home/saitoh183/.local/share/convos/convos.conf --listen http://*:8082
```

**Comment by saitoh183** [comment]
session_secrets =>    ['q4@sx#z!Vj5y']

Log: [warn] Using default (unsafe) session secrets. (Config file was not set up)

**Comment by jhthorsen** [comment]
Oh. "session_secrets" should just be "secrets". I've updated the webpage and test suite now.

**Comment by saitoh183** [comment]
Thanks it all works now...will update to new release when available
