### ISSUE TITLE
Can't scroll some pages, eg. list in Join dialog

### ISSUE THREAD

**Issue by 0racle** [Nordaaker/convos#331]
After you click on join dialog and get a list of channels, you cannot scroll that list of channels with the mouse. Using the cursor keys seems to navigate below the view, but the list doesn't scroll.

Also, the Help page text is longer than my screen and I can't scroll down. I can't read it unless I shrink the text smaller.

A scrollbar on these elements would be a welcome addition.

**Comment by jhthorsen** [comment]
That was a silly bug 😞 It will be fixed in the next release of Convos.

Thanks for reporting in!

**Comment by 0racle** [comment]
Thank you for the prompt response and fix.

**Comment by jhthorsen** [comment]
The "stable" branch is now up to date after I released version 0.99.30.

Hope this works as expected.
