### ISSUE TITLE
Convos gets K-Lined a lot

### ISSUE THREAD

**Issue by V3XATI0N** [Nordaaker/convos#333]
When there are multiple users connected to Convos all using the same IRC server, when Convos gets restarted those connections flood the IRC server, resulting in K-Lining the host, or if the host is allowed to have multiple connections, the flood results in connection throttling that never resolves.

Convos should implement some logic that tracks which servers it's connecting too and if there are multiple connections to a single server, it should internally delay those connection attempts so as to avoid getting itself k-lined and/or throttled.

**Comment by V3XATI0N** [comment]
turns out i was using CONVOS_CONNECT_DELAY wrong. so... problem doesn't actually exist.

**Comment by jhthorsen** [comment]
Could you provide a suggestion on how to make this clearer here: https://convos.by/doc/config.html#convos_connect_delay ?

What did you change CONVOS_CONNECT_DELAY to, and why?

**Comment by V3XATI0N** [comment]
I eventually had to push mine up to 25, first because everyone was getting K-lined (and there were only 3 or 4 of us), then at 15 we didn't get K-lined but were getting perpetually throttled for "reconnecting too fast". I don't know if that's reasonable for all servers though, this network might just be expecially paranoid about it.

**Comment by jhthorsen** [comment]
Yes, that sounds especially bad 😞. Can I ask which network it is?
