### ISSUE TITLE
Wishlist - define a logfile

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#337]
I wish to define a logfile for STDOUT (and STDERR). This could be done using command
line argument '--log /path/to/log.file' and/or environment $ENV{CONVOS_LOGFILE}.

Background: I start Convos with the systemd and this offers for me no optimal settings
for the output (STDOUT, STDERR, log to syslog or wherever, but no defined file).

Could you include this (optional) variable? Would also help with debugging. ;-)
It's not so important but it would be nice.

**Comment by jhthorsen** [comment]
I don't want it as a switch, but I will add as a config file parameter and environment variable.

**Comment by ukcb** [comment]
That would be great, thank you!

**Comment by jhthorsen** [comment]
This is now implemented and will be part of the next release, version 0.99_33.
