### ISSUE TITLE
Add environment variable for --listen

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#338]
I am looking for an ENV variable for the startup option --listen.

<pre>
# rgrep '$ENV{' convos | grep -i listen
convos/local/lib/perl5/Mojo/Server/Daemon.pm:has listen => sub 
{ [split ',', $ENV{MOJO_LISTEN} || 'http://*:3000'] };
</pre>

Can I use the variable $ENV{MOJO_LISTEN} without problems? If it were not better
to define a variable for Convos in the long term (e.g., $ENV{CONVOS_LISTEN}).

That would be the last variable that would be missing for my environment.conf
(environment.conf is a simple EnvironmentFile for systemd).

**Comment by jhthorsen** [comment]
Can't you just specify `--listen` instead as documented at https://convos.by/doc/config.html#listen ?

**Comment by ukcb** [comment]
I know the documentation. I would like to have a way to configure --listen as a config file parameter and/or environment variable. That would be nice. It is only a small wish.

**Comment by jhthorsen** [comment]
I'm not asking if you want. I'm curious about *why*.

**Comment by ukcb** [comment]
The only program option without a config file parameter or environment is --listen.
I would find it good, if one does not have to change the Convos start script but
only one option in the configuration file would need to change.
Here is my current setup for starting Convos over systemd. Why systemd? I do not want
to work with nohup; in addition, systemd restarts Convos in the event of an error.

I hope you come clearly with my broken English. :-)

`/etc/systemd/system/convos.service`
<pre>
[Unit]
Description=Convos Backend
After=network.target

[Service]
EnvironmentFile=/var/www/convos/environment.conf
ExecStart=/home/local/convos/script/convos daemon --listen "${CONVOS_APP_SERVER}"
User=www-data
Group=www-data
Restart=on-failure

[Install]
WantedBy=multi-user.target
# eof
</pre>

`/var/www/convos/environment.conf`
<pre>
#############################################################################
#
# This configfile is used by /etc/systemd/system/convos.service
#
# !!! IMPORTANT: If you edit here, do not forget to reload  !!!
# !!! the systemd service afterwards and restart the convos !!!
#
# systemctl daemon-reload
# service convos restart
#

#############################################################################
### SYSTEMD ENVIRONMENT
#############################################################################

### CONVOS_APP_SERVER #######################################################
### The local server where convos listens
###
CONVOS_APP_SERVER="http://127.0.0.1:3001"


#############################################################################
### CONVOS ENVIRONMENT
#############################################################################

### CONVOS_BACKEND ##########################################################
### Can be set to any class name that inherit from Convos::Core::Backend.
###
### Default: Convos::Core::Backend::File
###
#CONVOS_BACKEND="Convos::Core::Backend::File"

### CONVOS_CONNECT_DELAY ####################################################
### This variable decides how many seconds to wait between each
### user to connect to a chat server. The reason for this setting
### is that some servers will set a permanent ban if you “flood connect”.
###
### Default: 3
###
CONVOS_CONNECT_DELAY="3"

### CONVOS_CONTACT ##########################################################
### Used when rendering “Contact” links in the frontend.
###
### Default: mailto:root@localhost
###
CONVOS_CONTACT="mailto:root@localhost"

### CONVOS_DEBUG ############################################################
### Setting this variable to a true value will print extra debug information
### to STDERR. Another useful debug variable is MOJO_IRC_DEBUG which gives
### you IRC level debug information.
###
#CONVOS_DEBUG="1"

### CONVOS_DEFAULT_SERVER ###################################################
### Used to declare which server should be pre-filled when a user creates a
### new connection.
###
### Default: localhost
###
CONVOS_DEFAULT_SERVER="localhost:6697"

### CONVOS_FORCED_IRC_SERVER ################################################
### Will force any connection made to use this server. Note that this
### environment variable also overrride CONVOS_DEFAULT_SERVER.
###
### There is no forced IRC server by default.
###
#CONVOS_FORCED_IRC_SERVER="localhost:6697"

### CONVOS_HOME #############################################################
### This variable is used by Convos::Core::Backend::File to figure out where
### to store settings and log files.
###
### Default: $HOME/.local/share/convos/
###
CONVOS_HOME="/var/www/convos"

### CONVOS_INVITE_CODE ######################################################
### The value of this setting need to be used by the person who wants to
### register. It can be disabled by setting CONVOS_INVITE_CODE="".
### Check out the running guide for more details.
###
### The default value is a semi-random string.
###
CONVOS_INVITE_CODE="s3cret"

### CONVOS_ORGANIZATION_NAME ################################################
### Should be set to the name of the organization running this instance of
### Convos.
###
### Default: Convos
###
CONVOS_ORGANIZATION_NAME="Convos"

### CONVOS_ORGANIZATION_URL #################################################
### This variable will change the URL to the organization running this
### instance of Convos.
###
### Default: http://convos.by
###
CONVOS_ORGANIZATION_URL="http://convos.by"

### CONVOS_PLUGINS ##########################################################
### A list (comma separated) of perl modules that can be loaded into the
### backend for optional functionality.
###
### There are currently no plugins loaded by default.
###
#CONVOS_PLUGINS=

### CONVOS_SECRETS ##########################################################
### Should be set to list (comma separated) of random strings. This value is
### used to secure the Cookies written to the client.
###
### The default value is a semi-random secret.
###
CONVOS_SECRETS="super,duper,secret"

### CONVOS_SECURE_COOKIES ###################################################
### Should be set to true if Convos is served over HTTPS.
###
CONVOS_SECURE_COOKIES="1"

### MOJO_REVERSE_PROXY ######################################################
### The MOJO_REVERSE_PROXY environment variable can be used to enable
### proxy support, this allows Mojolicious to automatically pick up the
### X-Forwarded-For and X-Forwarded-Proto HTTP headers.
###
### Note that setting this environment variable without a reverse proxy in
### front will be a security issue. The FAQ has more details on how to set
### up Convos behind a reverse proxy server.
###
### Make convos available behind a reverse proxy
###
MOJO_REVERSE_PROXY="1"

### MORE debug - see CONVOS_DEBUG ###########################################
#MOJO_IRC_DEBUG="1"
#MOJO_LOG_LEVEL="debug"

# eof #######################################################################
</pre>

**Comment by jhthorsen** [comment]
Thank you for the detailed response! Based on this, I will document an environment variable you can use.

**Comment by jhthorsen** [comment]
MOJO_LISTEN is fine to use. I just added it to https://convos.by/doc/config.html#mojo_listen

**Comment by ukcb** [comment]
MOJO_LISTEN is not in your documentation. Do you have it commited? Is it still up to date?
