### ISSUE TITLE
Create connection is broken

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#339]
I installed a new version https://github.com/Nordaaker/convos/commit/452472fdcd1c4be43834e6134e66e3d5aafa7f26 today completely. I can not create a new connection - see screenshot. The buttons "Settings" and "Help" do not work. Login and Logout works.

![convos](https://cloud.githubusercontent.com/assets/22983914/25306758/1be2b746-2794-11e7-8190-053e58c8126c.png)

**Comment by jhthorsen** [comment]
That is awful! I need to improve https://github.com/Nordaaker/convos/blob/master/t/selenium-register.t

Will look at it later today.

**Comment by jhthorsen** [comment]
This is fixed in 0.99_34, by this commit: 6965793
