### ISSUE TITLE
Add TLS selector when creating a new connection

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#341]
The settings for TLS should already be possible when creating a new connection.

**Comment by jhthorsen** [comment]
I disagree. Convos automatically detects if TLS is available or not.

Why do you need this?

**Comment by ukcb** [comment]
For me, the two settings (server and TLS) simply belong together. If my server only listens on port 6697 (also not on 6667), then there is no automatic connection without TLS. Does Convos only automatically when an irc-server also listens on port 6667?

I find the options that are present when editing, should also be present when creating. Create is also only edit. :-)

**Comment by jhthorsen** [comment]
I find the TLS setting confusing for new users. Convos is all about making things as easy as possible.

The detection is not "try a range of ports", though that would be a cool enhancement. Today it's simply as dumb as this: Connect to the specified port and check if it can handle a TLS negotiation. If it can, then go on. If it cannot, then fallback to plain text.

**Comment by marcusramberg** [comment]
How about "Automatically uses a secure connection if supported" as a help text below the field?

**Comment by pink-mist** [comment]
@marcusramberg That sounds like a good solution. 👍

**Comment by ukcb** [comment]
What is the use of the help text when the automatic TLS detection does not work? To avoid confusing the users, you could hide the option TLS under the advanced settings. For me, the TLS option simply belongs to the server setup. A user would not be prompted if you could pre-define this option.
Would not it be a better idea in the long term if you simply say create a new connection and then display the window with the sidebar (as now when editing)? Then one would have the settings for a server in one place. For developers, one web interface would have to be better than two. You may think about it.
Sorry, I can't help much, am only admin and user, not a developer.

**Comment by marcusramberg** [comment]
@ukcb if automatic detection does not work, it should be fixed. That is a separate issue. Please open a new issue with details if that is the case.

**Comment by ukcb** [comment]
I have a little problem https://github.com/Nordaaker/convos/issues/345, which just does not allow me to make sense tests. I will not confuse you.

**Comment by jhthorsen** [comment]
I wonder if there's a misunderstanding here. How do you expect TLS detection to work @ukcb? Do you expect Convos to probe all the usual ports? If so, then TLS detection does not work, since I have failed to find a standard TLS port. Seems like different network use quite different ports for TLS.

**Comment by ukcb** [comment]
I do not want to try multiple ports. Convos is to use exactly the specified one port. Until now I did not know that there is an automatic TLS detection. I have always switched it on in the settings.
I will continue to test if the settings are saved correctly. I will tell you whether it works.

**Comment by jhthorsen** [comment]
I hope commit 0d1e75d explains that Convos will use TLS, if the server supports it.

Automatic TLS support have been fixed in 58a119e6.
