### ISSUE TITLE
username versus realname

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#342]
What is the purpose of the username? I do not see it in the irc server. This is only under Realname "Convos v0.99_xx". Should not the username appear there?

**Comment by jhthorsen** [comment]
The username is used here:

* https://metacpan.org/pod/Mojo::IRC#user
* https://metacpan.org/source/JHTHORSEN/Mojo-IRC-0.44/lib/Mojo/IRC.pm#L133

Meaning when you "start" a connection, these commands are sent:

```
PASS s3cretPassword
NICK your_nick
USER your_username 8 * :Convos v0.99_33
```

**Comment by jhthorsen** [comment]
Please join #convos on chat.freenode.net and ask questions.
