### ISSUE TITLE
Settings for forced connections

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#343]
Today again a wish. :-)

If you can define CONVOS_FORCED_IRC_SERVER, it would be logical to define
e.g. CONVOS_FORCED_IRC_SERVER_TLS = 0|1 and
e.g. CONVOS_FORCED_IRC_SERVER_PASSWORD = password 
When each connection is enforced, it is not necessary for anyone to set the values themselves.

What do you think about that?

**Comment by jhthorsen** [comment]
I will change the variable to take an URL, so you can write this:

irc://:password@irc.example.com?tls=1

**Comment by ukcb** [comment]
My goal is to define a forced connection for all users. A user should only be allowed to change their nickname and username, **but they are not allowed to change the server settings**. I would tolerate on connect commands. :)

**Comment by jhthorsen** [comment]
Why should they be able to change the username?

**Comment by jhthorsen** [comment]
This was harder to do, than what I thought in the beginning. Here are some comments/questions:

* CONVOS_FORCED_IRC_SERVER_TLS is not needed, since Convos will detect if the server supports TLS automatically.
* What is the usecase for CONVOS_FORCED_IRC_SERVER_PASSWORD?
* Why should they be able to change the username?
* What happens if a user enters another password? Should that override the password set in the forced URL?

**Comment by ukcb** [comment]
An automatic connection with TLS does not work for me, in my video https://github.com/Nordaaker/convos/issues/344 you can see this.  If the server is forced, the password belongs to it. The server password is the same for every user, he does not need to know when it is set.
The username I wanted to change, because I thought it changes the realname in a whois query.
It makes no sense if the user changes the password, there is only one server password.
For a forced server, the user should not change the server name, port, TLS, and password at all - otherwise it would not be forced.

A competing software (kiwiirc) knows e.g. the following settings:

// If set, the client may only connect to this 1 IRC server
//conf.restrict_server = "irc.example.com";
//conf.restrict_server_port = 6697;
//conf.restrict_server_ssl = true;
//conf.restrict_server_password = "pass";

This works well, but I did not want to use this software.
I miss this in Convos.

**Comment by jhthorsen** [comment]
I've implemented the possibility to set the password now. See https://github.com/Nordaaker/convos/blob/master/t/selenium-register-forced.t#L7 for example string.

Will revisit #344 soon.
