### ISSUE TITLE
Problem with saving the server settings

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#345]
I log in for the first time and see the defaults for a new connection,
server: **localhost**:6697
nick: toor
Then I change the value for the server: **any-server**:6697
I set the advanced options for Username and Password.
When I click on Create, I see the Join dialog and the message:
"Could not load rooms from irc-**localhost**: Not connected."

I can now edit the server **localhost**. The name of the server is now **localhost**:6697 but it should be **any-server**:6697.

If I delete the connection irc-**localhost** I see the "Welcome to Convos!" side with the default server **any-server**:6697

**Comment by jhthorsen** [comment]
What's the difference between this and #344?
