### ISSUE TITLE
Document the WebSocket API

### ISSUE THREAD

**Issue by 0xAF** [Nordaaker/convos#348]
The subject says it all.

**Comment by jhthorsen** [comment]
Could you tell me a bit about what you want to do with the API? I know this have been on my TODO list for quite some time, but hearing about what you want to know will push me to prioritize this.

I could also just tell you what you need, if this is a blocker for what you want to accomplish.

**Comment by 0xAF** [comment]
Sorry for being so short.
My idea is to create (or at least try to) a Chrome App, which will allow the browser to communicate with Convos in background. No need to have the Convos page open. The background communication via this app will notify the user when Convos has notifications and will allow the user to run the app in no-browser mode, i.e. like a desktop app. Or at least that's what I would want to achieve. I'm still unfamiliar with Chrome Apps, but I'm planing to learn a bit more about it and Convos is a great way to get some experience in that area.
This app would need to communicate with Convos for the notifications in first place, but perhaps it can be extended to more functionality in later stages.
Think of this more like as Desktop app, which is minimized in the system tray and notifies you of some event, like Skype for example. Once you open the app, it will actually open the Convos page.

Note: Don't get too much excited about this, because my knowledge on Chrome Apps is at the minimum, I just know there are some similar stuff already made. And I'm critically low on free time, so no promises for now. The request is just a push on your TODO list. Once I start working on this, I will push more. :)

**Comment by jhthorsen** [comment]
The websocket API is now documented and available online here: https://convos.chat/doc/Convos/Controller/Events#api
