### ISSUE TITLE
Manual install without commandline on shared host?

### ISSUE THREAD

**Issue by poVoq** [Nordaaker/convos#354]
Is is possible to install Convos on a shared host that provides perl (ovh) but no ssh access?

I was able to install for example Foswiki on it just fine and that one also runs with perl.

Or is there a specific requirement that would make this not feasible? I will host the IRC server on a different machine with better access.

**Comment by marcusramberg** [comment]
Because of the persistent async nature of convos it needs to run as a daemon rather than inside your web server.
