### ISSUE TITLE
Joins, parts, quits and nick changes not being displayed

### ISSUE THREAD

**Issue by TheMythPT** [Nordaaker/convos#355]
I've notice, after reattaching to a convos session, that we don't have any backlog about joins, parts, quits nor nick changes.
That would be pretty handy to have that information being displayed after reattach.
Is that a feature or a bug?

**Comment by marcusramberg** [comment]
Yeah, this is working as intended, because we don't consider this important enough information to save.

**Comment by TheMythPT** [comment]
well, for me as a network admin, for channel operators, that's a very important information to save. also joins/quits/parts with ident@hostname.
you should really consider this as a option to enable on the config.
but overall is a good work you've done.

**Comment by marcusramberg** [comment]
I can see that, and I'd be happy to accept a PR to support this as a config option, but it's just not something I'm going to prioritize as I don't need it. 😺

**Comment by TheMythPT** [comment]
I do understand that. but it would be an interesting feature, I suppose.
I'd be glad to help if I did understand anything about programming, which I don't.
maybe you can add this into the todo list. :)

**Comment by jhthorsen** [comment]
I'm going to add support for this when I change the backend to SQLite/Postgres/MySQL.

**Comment by jhthorsen** [comment]
I'm replacing this with #187.
