### ISSUE TITLE
Password dialog for protected channels should hide the password

### ISSUE THREAD

**Issue by ukcb** [Nordaaker/convos#358]
You can see the password in the plaintext if you want to enter a protected channel.
Please make invisible. I use the stable branch.

![pass](https://user-images.githubusercontent.com/22983914/29251154-a0bc864e-8050-11e7-8067-1530820a867f.png)

**Comment by marcusramberg** [comment]
Fixed in master.

**Comment by jhthorsen** [comment]
I forgot to add handling of +r channels in 1.00.
