### ISSUE TITLE
Support international symbols

### ISSUE THREAD

**Issue by jsnfwlr** [Nordaaker/convos#359]
`[W|A] convert \:0e3f5.52  (bitcoins) to Australian dollars = Au$28670  (Australian dollars)`

Should show as

`[W|A] convert ฿5.52  (bitcoins) to Australian dollars = Au$28670  (Australian dollars)`

**Comment by marcusramberg** [comment]
Literal ฿ works well afaict, are you asking for  '\:0e3f5.52' to be converted to ฿? Is this a common syntax for unicode code-points?

**Comment by jsnfwlr** [comment]
I was using The Wolfram Alpha IRC bot and that's how it showed up, it worked fine on mIRC


On 23 Aug. 2017 13:59, Marcus Ramberg <notifications@github.com> wrote:

Literal ฿ works well afaict, are you asking for ':0e3f5.52' to be converted to ฿? Is this a common syntax for unicode code-points?

**Comment by jhthorsen** [comment]
This could be implemented at the same place as where we handle mIRC colors: https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L584

I will accept a PR for this feature. Something like this I suppose:

```
$msg->{params}[1] =~ s/\\:([a-fA-F0-9]{4})/{pack "U", hex $1}/ge
```

Need some real life testing and a unit test. The unit test can be added here: https://github.com/Nordaaker/convos/blob/d9b369f5af60adc4981b78ee269a76fb51e71c9b/t/web-irc-events.t#L96

**Comment by jhthorsen** [comment]
I'm closing this because no real data has been provided, and I don't understand the issue.
