### ISSUE TITLE
Additional semicolon added in text after url

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#362]
after pasting an example into the channel the representation I saw added a semicolon which it seems wasn't pasted to others (thank goodness). That said it is curious. It is likely related to embedding and thus may be about LinkEmbedder but I am going to start it out here for the time being. 

![screen shot 2017-10-30 at 1 34 09 pm](https://user-images.githubusercontent.com/735765/32189038-88de6254-bd77-11e7-8af9-83b9d22fb8a8.png)

https://irclog.perlgeek.de/mojo/2017-10-30#i_15376130

**Comment by jhthorsen** [comment]
Adding the actual IRC log inline:

```
18:32 <jberger> well that was exciting
18:32 <jberger> for the log, I tried `mojo get 'http://tcdecks.net/format.php?format=Pauper' title text` and it worked fine for me
18:33 <jberger> odd where did that semicolon come from?
18:33 <jberger> looks like a strange convos artifact
```
