### ISSUE TITLE
Ubuntu 16.04.3 - Snap doesn't setup correctly

### ISSUE THREAD

**Issue by JoeArcher007** [Nordaaker/convos#363]
I recently just installed this snap on an Amazon EC2 free tier instance. I know it's not the best setup, but thought it would work great for this purpose.

I have installed with sudo snap install convos, but afterwards, it's not working. I go into where the snap is installed and try to run the script ./convos install but it fails at Mozilla::CA

The below is the uname -a of the server. If you require any more information please let me know.

Thanks!

Linux Server 4.4.0-1039-aws #48-Ubuntu SMP Wed Oct 11 15:15:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jhthorsen** [comment]
I'm going to close this issue, because it's old. Please do let me know if this should still be fixed.
