### ISSUE TITLE
Unicode::UTF8 missing

### ISSUE THREAD

**Issue by reaperofpower** [Nordaaker/convos#370]
Any ideas what I am missing?

```
root@server:~# curl https://convos.by/install.sh | sh -                                     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1186    0  1186    0     0   1783      0 --:--:-- --:--:-- --:--:--  1783
mkdir: cannot create directory 'convos': File exists
> /usr/bin/curl -s -L https://github.com/Nordaaker/convos/archive/stable.tar.gz | /bin/tar xz -C convos --strip-components 1
> /usr/bin/perl convos/script/convos install
>>> /usr/bin/perl /root/convos/script/cpanm -n -l /root/convos/script/../local -M https://cpan.metacpan.org Mojo::IRC
--> Working on Mojo::IRC
Fetching https://cpan.metacpan.org/authors/id/J/JH/JHTHORSEN/Mojo-IRC-0.45.tar.gz ... OK
Configuring Mojo-IRC-0.45 ... OK
==> Found dependencies: Unicode::UTF8
--> Working on Unicode::UTF8
Fetching https://cpan.metacpan.org/authors/id/C/CH/CHANSEN/Unicode-UTF8-0.62.tar.gz ... OKConfiguring Unicode-UTF8-0.62 ... OK
Building Unicode-UTF8-0.62 ... FAIL
! Installing Unicode::UTF8 failed. See /root/.cpanm/work/1529973851.1104/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Unicode::UTF8' is not installed
! Bailing out the installation for Mojo-IRC-0.45.
cpanm failed!
root@server:~#
```

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

Possibly related issues are https://github.com/Nordaaker/convos/issues/309 (Missing /LIST command), https://github.com/Nordaaker/convos/issues/130 ([ missing in nicks), https://github.com/Nordaaker/convos/issues/23 (AssetPack missing preprocessors), https://github.com/Nordaaker/convos/issues/274 (Placeholder: Improve / add missing information to https://convos.by), and https://github.com/Nordaaker/convos/issues/266 (Installation on CentOS7 fails on missing Time::Piece).

**Comment by jhthorsen** [comment]
I don't know, but maybe you can look in `/root/.cpanm/work/1529973851.1104/build.log` to see what's going on? I found that log file by looking at the lines starting with "!" in your output.

**Comment by wilmardo** [comment]
I had to install `gcc` to overcome this error. The error is somewhat non descriptive, when you look in the build log it complains about a missing C compiler.

I also had to install (in a LXC container so it might be not needed on a full blown VM): 
* `make`
* `libnet-ssleay-perl`
* `libcrypt-eksblowfish-perl`

Might be useful to document this somewhere?

**Comment by jhthorsen** [comment]
Going to replace this with #392.
