### ISSUE TITLE
Link detection fails with emoji in the url.

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#371]
For instance https://folk.uio.no/marcusr/skitch/When_You_Were_Young_-_YouTube_Music_🔊_20E4C926.png is cut off at the emoji.

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

Possibly related issues are https://github.com/Nordaaker/convos/issues/186 (More better emoji support?), https://github.com/Nordaaker/convos/issues/22 (Websocket fail to reconnect), https://github.com/Nordaaker/convos/issues/18 (Improve link handling), https://github.com/Nordaaker/convos/issues/122 (Docker build fails), and https://github.com/Nordaaker/convos/issues/307 (Cannot modify the Organization URL).

**Comment by jhthorsen** [comment]
@marcusramberg: I'm not sure how to reproduce this. Can you give me the raw IRC message, or another way to reproduce it?

Or even better: Maybe this isn't a bug in 1.00 😄

**Comment by marcusramberg** [comment]
Fixed In 1.0
