### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by tobytteh** [Nordaaker/convos#375]
Just FYI: http://convos.by doesn't resolve. Looks like it expired on the 30th of November!

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

**Comment by marcusramberg** [comment]
Oops. Gotta train google to not bury mails from domains.by. Renewed for another two years. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
