### ISSUE TITLE
Does not connect to ZNC

### ISSUE THREAD

**Issue by arch1mede** [Nordaaker/convos#376]
Currently when connecting to a BNC like ZNC, it will try multiple times very rapidly and trigger a flood attack and block you from connecting. I have been unable to connect to it and have since abandoned using it.

Additionally when using the docker image, when I did try it and it didn't work and I removed it, connecting to it (docker image) I could see the console messages and it was still attempting to connect.

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

Possibly related issues are https://github.com/Nordaaker/convos/issues/305 (Does not support "away" ?), https://github.com/Nordaaker/convos/issues/210 (delete_user() does not kill connections), https://github.com/Nordaaker/convos/issues/233 (Convos does not respond to CTCP commands), https://github.com/Nordaaker/convos/issues/222 (Action "stop" does not work for a connection), and https://github.com/Nordaaker/convos/issues/73 (Cannot close chat tab if not connected to server).

**Comment by jhthorsen** [comment]
I'm going to close this, since I don't know anything about ZNC 😞 

Let me know if you still have issues.
