### ISSUE TITLE
handle +r channels

### ISSUE THREAD

**Issue by Svetlana-T** [Nordaaker/convos#377]
some channels require registration to join and Convos does not join them because there is no way to identify to NickServ before joining, for example I think #firefox at freenode ( join it, disconnect from freenode and then connect again ) these channels are identified by channel mode +r

**Comment by marcusramberg** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jhthorsen.

Possibly related issues are https://github.com/Nordaaker/convos/issues/284 (Connection::Irc need to handle channel redirects), https://github.com/Nordaaker/convos/issues/190 (Handle notice), https://github.com/Nordaaker/convos/issues/87 (Better handling of being kicked from a channel.), https://github.com/Nordaaker/convos/issues/91 (Cmd + T navigation for channels and queries), and https://github.com/Nordaaker/convos/issues/159 (Handle password protected connections).

**Comment by SvetlanaTkachenko** [comment]
I think that these issues appear to not be related.

**Comment by marcusramberg** [comment]
Under advanced you can set 'on connect commands'. I have '/msg nickserv identify password' there.

**Comment by SvetlanaTkachenko** [comment]
@marcusramberg thanks for the suggestion. 

I have tried to add '/msg nickserv identify password' and '/join #octave' to freenode network and re-connect, however it did not rejoin #octave channel (which is +r). The error message is

`#octave Cannot join channel (+r) - you need to be identified with services - see https://freenode.net/kb/answer/registration`

I checked the nickserv chat, in there I am identified correctly, however it may be a race condition.

Adding '/join #octave' to onconnect commands does not change the symptoms.

**Comment by Wikiwide** [comment]
I have added '/msg nickserv identify password' to irc-freenode, will see how it goes.

**Comment by Wikiwide** [comment]
Not working so far. I guess I will have to chain "/join ##channel" after "/msg NickServ Identify Password" within on-connect commands.

**Comment by Wikiwide** [comment]
Still not re-connecting automatically to channels, despite on-connect commands. No idea why, but it doesn't work.

**Comment by SvetlanaTkachenko** [comment]
I would be glad to implement either of these two

- /pause command (which does nothing other than just sit there for 15 seconds) as an ugly workaround, or
- SASL authentication ( https://freenode.net/static/files/cz_sasl.js is an example of its implementation for another IRC client )

@marcusramberg and @Nordaaker any guidance about this would be appreciated. In which file do I put a new command and in which file can I add the hooks necessary for SASL commands. I am in #convos channel when not affected by the bug - for now I have to manually rejoin it each time I lose internet connection. Thank you in advance!! :)

**Comment by jhthorsen** [comment]
This works for me when setting the following for "On-connect commands" in 1.00, which was released yesterday:

```
/msg NickServ identify supersecretpassword
/join #convos
/msg chanserv op #convos
```

@Svetlana-T: I don't want to add "/pause", but maybe we could add "/sleep 15". Please open a new issue where you describe what this might solve, if you still need it.

The SASL part seems to be covered in #350.
