### ISSUE TITLE
cpanm is not executable by default

### ISSUE THREAD

**Issue by saraf** [Nordaaker/convos#378]
The documentation recommends installing the optional EV module here:
https://convos.by/doc/getting-started.html#optional-modules

using
```
$ ./script/cpanm --sudo EV
```

The ./script/cpanm file,  is not executable and we get a `-bash: ./script/cpanm: Permission denied` error.
Fixed trivially by `chmod +x`

./script/cpanm should be made executable by default.

[I was not sure about git retaining file permissions](https://stackoverflow.com/questions/3207728/retaining-file-permissions-with-git) - but the ./script/convos file, however, IS executable - which makes one think that this is possible to achieve.

**Comment by jhthorsen** [comment]
Thanks! It can't be executable though, since I don't want that script to be installed, so instead I updated the documentation.
