### ISSUE TITLE
Send service account messages to connection dialog

### ISSUE THREAD

**Issue by Svetlana-T** [Nordaaker/convos#379]
Is it possible to configure convos to not open a separate window for private notices, please? Having to close off nicksev chanserv etc is a bit annoying.

**Comment by jhthorsen** [comment]
I'm not sure if I understand... Where do you want these notices to go? And how can Convos know if it's "nickserv" or "chanserv" and not a normal user?

Would it work if we actually hard coded "nickserv" and "chanserv" and forced those messages to go into the server log? If so, what do we do about password messages?

**Comment by Svetlana-T** [comment]
It would be great if these messages went to irc-freenode buffer instead

**Comment by jhthorsen** [comment]
I don't think I want this after thinking about it a bit more: Some of these messages contain sensitive information that I want to hide, meaning I don't want it to be always visible by accidentally visiting the connection conversation.

I do think I would like to have it though, if I could delete the messages somehow, but I don't see how that would be doable with the file backend. It is rather annoying to close those conversations every time I reconnect.

@marcusramberg: What do you think? Got any ideas on how to fix this?

**Comment by jhthorsen** [comment]
I have a hard time figuring out how to model this in a simple way, so I'm putting this issue in the [fridge](https://github.com/Nordaaker/convos/milestone/20).

**Comment by jhthorsen** [comment]
I think this would be a great enhancement to the user experience. I'm not quite sure how to do it, but maybe we can add a list of nicknames that would go into the main server chat? It could even be configurable.

**Comment by jberger** [comment]
I can imagine a configurable list of "service accounts" per connection or so

**Comment by jhthorsen** [comment]
I'm going to close this issue, since #532 is ready for review.
