### ISSUE TITLE
Add nickserv certfp authentication

### ISSUE THREAD

**Issue by Svetlana-T** [Nordaaker/convos#380]
https://freenode.net/kb/answer/certfp

https://www.oftc.net/NickServ/CertFP/

Would be nice to have, as some channels require authentication prior to joining and for the lack of a working automatic identification option, currently I have to join them by hand.

**Comment by Wikiwide** [comment]
Would be nice. Especially taking into account that I regularly see disconnections (for whatever reasons), and client, annoyingly, is unable to automatically rejoin the channel.

**Comment by jhthorsen** [comment]
Does that mean we should have two new fields in the connection settings, where you can upload a private and public key? If, so I think the building blocks are in place:

* 69213a66 has logic for uploading files that should only be accessible from the server.
* 26bbf628d has logic for reading tls_cert and tls_key, which could come from the files uploaded.

**Comment by jhthorsen** [comment]
This should be implemented in 5.07.
