### ISSUE TITLE
stop hiding a half of the last line in the chat view

### ISSUE THREAD

**Issue by Svetlana-T** [Nordaaker/convos#381]
In the channel discussions, a half of the last line is always covered by the input box. This started happening about a week ago after I upgraded Convos. This issue is absent in Chromium, but present in Firefox.

**Comment by marcusramberg** [comment]
Could you provide a screenshot so I understand the problem better?

**Comment by Mirodin** [comment]
Not OP but I can confirm that this happens in FF 66.0.2.

![Screenshot_2019-04-07 Convos for Nordaaker](https://user-images.githubusercontent.com/2410346/55689909-0b2ea800-597a-11e9-9945-d9e9f52672c9.png)

**Comment by dotandimet** [comment]
I think there's an 8px top padding on the convos-input class that is causing it.

**Comment by jhthorsen** [comment]
This is super annoying, but luckily not an issue in the "beta" branch 👍
