### ISSUE TITLE
Allow admin to set suggested channels per network?

### ISSUE THREAD

**Issue by poVoq** [Nordaaker/convos#385]
Would be cool if there was some easy way to link multiple channels in the side pannel, a bit like it is found in Slack or Discord and which can be set by the admin or some sort of group leader.

Just to make on boarding for new users easier and give a familiar and pre-populated channel view to them.

**Comment by jhthorsen** [comment]
I totally agree. What I would like to do are...

1. I kind of want to remove the whole "set up server" part when a user register. I would rather have Convos automatically connect to a preferred server, and optionally join a set of channels. It should be fairly simple to do with something like https://convos.by/doc/config.html#convos_default_server
2. I would like to add support for https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers which ask to register "irc:" protocol links.
3. The beta branch already have (partial) support for adding dialogs and connections from custom links, but I would like to add support for invite links. Something like https://demo.convos.by/join?server=freenode&dialog=foo&dialog=bar&token=supersecret

**Comment by jhthorsen** [comment]
I also think that the default server should be the convos provided demo server, but I have to discuss it over with @marcusramberg first.

**Comment by jhthorsen** [comment]
@poVoq: 1.00 has support for setting a custom CONVOS_DEFAULT_CONNECTION environment variable, which includes a channel name. This will be used for adding a default connection to a newly created user, and also make that user join a channel, if present. The default value is: `irc://chat.freenode.net:6697/%23convos `.
