### ISSUE TITLE
Limit message length in Convos, so that user knows clearly when message has to be split and sent as two messages

### ISSUE THREAD

**Issue by Wikiwide** [Nordaaker/convos#386]
"IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair, and these messages shall not exceed 512 characters in length, counting all characters including the trailing CR-LF. Thus, there are 510 characters maximum allowed for the command and its parameters." -> https://www.ietf.org/rfc/rfc1459.txt

I send a 515-characters-long (not including commands or parameters) text message to IRC channel, Convos doesn't stop me, doesn't even hint that the message has been truncated by server.

Could you please fix it?

**Comment by jhthorsen** [comment]
How do you propose to fix it? Should the textarea (where you write the message) show up as red, and also not allow the message to be sent, or should the text simply be split into two messages on the server side?

I'm open to other suggestions as well 👍

**Comment by Wikiwide** [comment]
I would appreciate if Convos could split long message into short messages before sending them to IRC server such as freenode.
I am not sure whether message splitting should be done on user's computer, or on Convos server, but webpage should display to user the number of characters in the long message, and the number of short messages which would be produced from the long message.

**Comment by jhthorsen** [comment]
I implemented the splitting on the server side.

It will be available when I release 1.02 🎉
