### ISSUE TITLE
Can't ignore invalid SSL certificates

### ISSUE THREAD

**Issue by V3XATI0N** [Nordaaker/convos#398]
Trying to connect to a server with a self-signed certificate, Convos fails with "SSL connect attempt failed error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed", even if the "Verify SSL certificate" checkbox is NOT checked. This makes convos completely unusable.

**Comment by jberger** [comment]
I'm not sure if it is documented in the convos documentation (if not it should be so I won't close this ticket yet), but mojolicious, the undelying server behind convos has a way to disable ssl verification: https://mojolicious.org/perldoc/Mojolicious/Guides/FAQ#What-does-the-error-...certificate-verify-failed-mean . TLDR, set `MOJO_INSECURE=1` in your environment before starting convos and you should be fine.

**Comment by V3XATI0N** [comment]
Thanks for the tip, but this has no effect. I tried adding `export MOJO_INSECURE=1` to `startconvos.sh`, and I also tried setting the variable from the CLI when running startconvos.sh. In both cases the same "certificate verify failed" error occurs.

**Comment by jberger** [comment]
What does `startconvos.sh` contain? I don't have that file here. If it starts convos via docker you probably need to set it via docker somehow.

**Comment by V3XATI0N** [comment]
It just sets variables and starts the daemon. But... actually I was just able to get it working by completely reinstalling. Something must have been screwed up in the Mojo libs or something. Thanks for your help!
