### ISSUE TITLE
Unable to track your nick changing

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#399]
If you /nick something you will be marked as offline in the chat dialog.

**Comment by jhthorsen** [comment]
How do you propose tracking this?

**Comment by marcusramberg** [comment]
periodic /whoami calls? Or tracking /nick sent to server?

**Comment by jhthorsen** [comment]
So you only want to implement this for your own user, and not for everyone? What happens if someone else takes your old nick and then leaves?

**Comment by marcusramberg** [comment]
I would think nothing happens? But maybe we do need this tracking of nick changes for all users/channels to keep the user list correct.

**Comment by jhthorsen** [comment]
I don't see how to implement this, so I'm putting this issue in the [fridge](https://github.com/Nordaaker/convos/milestone/20).

Maybe it's better to focus on getting some of the features in #444 in.
