### ISSUE TITLE
Potential for highlight on every message

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#403]
So I just had a problem where I was being highlighted on every message. The cause was that when I saved my user config, it saved `[""]` for the highlight_keywords rather than `[]`. This meant that because of [the way that value is used](https://github.com/Nordaaker/convos/blob/c470e5d59d88f6730c5026c75b0a3a99ffd7a00c/lib/Convos/Core/Connection/Irc.pm#L618-L619) it was matching every line.

I suggest changing [that line](https://github.com/Nordaaker/convos/blob/c470e5d59d88f6730c5026c75b0a3a99ffd7a00c/lib/Convos/Core/Connection/Irc.pm#L618-L619) to 

```perl
$highlight = grep { $msg->{params}[1] =~ /\b\Q$_\E\b/i } $self->_irc->nick,
      grep { length } @{$self->user->highlight_keywords};
```
as a sanity check, and also changing the user save function to not write in an empty line there, even if the incoming request seems to suggest it.

**Comment by jhthorsen** [comment]
Thanks! Sorry for the inconvenience.

**Comment by jberger** [comment]
No worries, glad you nipped it in the bud!
