### ISSUE TITLE
Multi-language User Interface

### ISSUE THREAD

**Issue by serhack** [Nordaaker/convos#422]
Several people like Convos, but one of the main obstacles for them is to use Convos in English. I'm Italian, and I think it would be very appreciated if you can add the option of translations of User Interface.

**Comment by jhthorsen** [comment]
Will you contribute translations if I enable you to?

**Comment by serhack** [comment]
Naturally yes!

**Comment by jhthorsen** [comment]
The commit d05693ff0ced2bda98a8254ef21fa4e7b3701e1d contains a po file for English. If you want to start doing translations, I suggest that you copy that file to something like "it.po" and open a PR once the translation is done.

I still haven't done the integration in the frontend, but I have a pretty good idea how I will do that, and I will certainly do it if a PR is created with translations.

**Comment by jhthorsen** [comment]
Please do let me know if the en.po file seems to contain some sort of bugs or if some of the strings could be merged.

**Comment by ivan-avalos** [comment]
Added Spanish translation: #545

**Comment by jhthorsen** [comment]
@serhack: Want to create a .po file? 😄 

I'm going to close this now, since the logic is in place. Translations can go directly into pull requests.
