### ISSUE TITLE
"/mode #channel +o nick" is broken.

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#429]
**Describe the bug**
Trying to op someone is broken. It applies whatever channel modes it can get from the nick.

**To Reproduce**
1. Join #kindone123
2. Get op.
3. "/mode #kindone123 +o KindOne
4. 
irssi: 
15:09:05 -!- KindTwo sets mode: +kio +o KindOne
convos: 
+o got mode +kio from KindTwo.

**Expected behavior**

convos: 
KindOne got mode +o from KindTwo

**Comment by jhthorsen** [comment]
See the https://github.com/Nordaaker/convos/issues/430#issuecomment-569370557 comment for an explanation.

**Comment by RealKindOne** [comment]
>make it more simple and intuitive (IMO)

I disagree with that. I've been using mIRC for over 12 years and irssi for about 6 years, they require the channel name, its a bit difficult to change to something that does will not accept it. I do not like clients that play "smart" by removing the channel name requirements. I prefer the "dumb" clients that explicitly require the channel name, even if its being performed in the active channel. 

Use case for including a channel name:

You are chatting in #foobar and you are op in #whatever. Someone in #foobar asks for voice in #whatever. You can just "/mode #whatever v someone" in the #foobar chat box without having to switch into #whatever channel. voice them,  and switch back into #foobar when done.

**Comment by jhthorsen** [comment]
Thanks for taking the time to disagree 😄 

I've changed the logic in 93ae2c14, allowing both ways to work.
