### ISSUE TITLE
Autocomplete for "/mode" is wrong.

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#430]
**Describe the bug**

>/mode +o #channel nick

Performing a command as suggested will fail.

>##kindone123 No such nick/channel

**To Reproduce**
1. Type /mode

**Expected behavior**
Should show: 

>/mode #channel .+o nick

**Comment by jhthorsen** [comment]
Even though its sure is a bug, then the solution is not quite correct: That will only work, if you are in the connection conversation, since the active channel you're in is inserted after "MODE" to make it more simple and intuitive (IMO)

 fd4f836 has this help message:
> /mode [+|-][b|o|v] <user>
