### ISSUE TITLE
Convert unix timestamps on bans/invites/exempts to something human readable.

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#431]
**Is your feature request related to a problem? Please describe.**
Currently the timestamps for bans are in unix time. Having to convert those on a website into a human readable format is a bit annoying.

```
/mode #channel b
#channel *!*@foobar.com weber.freenode.net 1576705311
```

**Describe the solution you'd like**
```
/mode #channel b
#channel *!*@foobar.com weber.freenode.net December 18, 2019 16:41:51
```

**Describe alternatives you've considered**
Allow options for various time formats.

Dec 18, 2019 4:41:51 PM
12/18/19 4:41:51 PM

**Additional context**

**Comment by jhthorsen** [comment]
Thanks for reporting in! "ban modes" is not something I've used myself, so this part of Convos hasn't received any love. I hope 1b5f313 improves this in version 3.01.
