### ISSUE TITLE
Setting and returning banlist, exceptlist, invitelist and quietlist does not work as expected

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#432]
**Describe the bug**
Anyone adding channel bans will cause them to be added into the participants list

**To Reproduce**
1. From another irc client, ```/mode #channel bb *!*@foobar.com *!*@example.com```
2. Look at the channel from convos.
3. ```*!*@foobar.com``` and ```*!*@example.com``` are now on the participants list.

**Expected behavior**
On the ban list, not the participants list.

**Comment by jhthorsen** [comment]
This is fixed in 1b5f313. Will be part of the 3.01 release.

**Comment by RealKindOne** [comment]
Invite (I) and Exempt (e) are in RFC2812.

https://tools.ietf.org/html/rfc2812


Quiet (q) is is IRCd specific (Charybdis and forks).


Adding entires to the lists:

```
/mode ##kindone123 I $a:KindOne
/mode ##kindone123 e $a:KindOne
/mode ##kindone123 q $a:KindOne
```

Viewing:
Note: You need to be op in the channel if you want to view the Invite and Exempt list. 
```
/mode ##kindone123 I
```
```
:livingstone.freenode.net 346 KindOne ##kindone123 $a:KindOne KindOne!kindone@i.hate.packets 1577480045]
:livingstone.freenode.net 347 KindOne ##kindone123 :End of Channel Invite List]
```

```
/mode ##kindone123 e
```
```
:livingstone.freenode.net 348 KindOne ##kindone123 $a:KindOne KindOne!kindone@i.hate.packets 1577510867]
:livingstone.freenode.net 349 KindOne ##kindone123 :End of Channel Exception List]
```
```
/mode ##kindone123 q
```
 Note: this includes a "q" after the channel.
```
:livingstone.freenode.net 728 KindOne ##kindone123 q $a:KindOne KindOne!kindone@i.hate.packets 1577512013]
:livingstone.freenode.net 729 KindOne ##kindone123 q :End of Channel Quiet List]
```

**Comment by jhthorsen** [comment]
Thanks for the detailed bug report! I changed the title, so you don't have to re-open #431 as well.

Could you also provide examples of what you would like the output to be like?

**Comment by RealKindOne** [comment]
```
/mode ##kindone123 Ieqb
```
```
##kindone123 Invite $a:KindOne set by KindOne!kindone@i.hate.packets on (Sat, Dec 28, 2019 12:46:53)
##kindone123 End of Channel Invite List
##kindone123 Exempt $a:KindOne set by KindOne!kindone@i.hate.packets on (Sat, Dec 28, 2019 12:27:47)
##kindone123 End of Channel Exempt List
##kindone123 Quiet $a:KindOne set by KindOne!kindone@i.hate.packets on (Sat, Dec 28, 2019 12:46:53)
##kindone123 End of Channel Quiet List
##kindone123 Ban $a:KindOne set by KindOne!kindone@i.hate.packets on (Sat, Dec 28, 2019 12:46:53)
##kindone123 End of Channel Ban List
```

Includes Invite/Exempt/Quiet/Ban after the channel name so you can easily see what it is, if it fills up the screen and you can't find the "End of Channel ... List"

Some people might want different timestamp formats.

**Comment by RealKindOne** [comment]
Looks like  [1b5f313](https://github.com/Nordaaker/convos/commit/1b5f313cad6ad512c41473b18caf36bdd5a45894) broke viewing the ban list if you include a channel name.


Works, inside a channel:
```
/mode b
```


Does not work, even if channel is active.
```
/mode ##kindone123 b
```

Need to be able to include a channel name if I want to check the ban list of another channel to see why I or someone else cannot join/speak.
