### ISSUE TITLE
Cannot change theme in Chromium/Chrome/Firefox on desktop.

### ISSUE THREAD

**Issue by RealKindOne** [Nordaaker/convos#434]
**To Reproduce**
1. Go to Account Settings.
2. Try changing Theme.
3. Click Dark, Light, or Node.
4. Nothing happens.

**Expected behavior**
Able to select another theme.

**Screenshots** - Debian / Chromium 71...
![ezgif-1-a8fb9ea9b754](https://user-images.githubusercontent.com/20209685/71549847-80239100-2992-11ea-913a-5b7431bf1094.gif)

**Environment:**
  OS: Debian 10 64bit
  Browser: Chromium
  Version: 71.0.3578.80

Also Replicated in: 

  OS: Debian 10 64bit
  Browser: Firefox
  Version: 68.2.0esr
.....
  OS: Windows 7 SP1 64bit
  Browser: Chrome
  Version: 79.0.3945.88

**Comment by jhthorsen** [comment]
Thanks for the bug report. Should be fixed in 3.02.
