### ISSUE TITLE
Problem with names starting with "_"

### ISSUE THREAD

**Issue by fjullien** [Nordaaker/convos#438]
Convos can't deal with nicks that include underscores.
For example, `_myNick_` is interpreted as `myNick`.

**Comment by jhthorsen** [comment]
@marcusramberg: I suggest removing markdown support for "_" and only support "*". By doing that, I can also removing the special handling for "__END__".

https://github.com/Nordaaker/convos/blob/master/assets/js/md.js#L117

So there's three alternative ways to fix this: (That I can come up with)

1. Remove support for "_" completely (I think I like this the most)
2. Look at the nick list and cancel out markdown formatting if the string in the message, matches a nick. The problem with this is that it won't work after the person has quit/parted the channel
3. Look at the surrounding messages and see who is the sender. I think this will work in most cases, but it could have some edge cases... It still wouldn't work if you say "jhthorsen: contact that person by sending /msg \_myNick_ hey!", and that person is not in the channel or has not been active in a while.

**Comment by pink-mist** [comment]
I suppose I prefer ```1```, but I'm still worried about nicks with ```[ ]```

**Comment by marcusramberg** [comment]
I also prefer no. 1

**Comment by fjullien** [comment]
I think there is may ba another problem related to this.
I updated my version to v3.08 but there is still a problem when connecting to freenode:

![Capture du 2020-02-02 20-26-25](https://user-images.githubusercontent.com/1468818/73613975-3bc38a80-45fb-11ea-9c71-8f119e78a2ca.png)

Looks like it tries to connect with ~_franck_
