### ISSUE TITLE
Convos 3.08 not loading in Microsoft Edge 44.18362.449.0

### ISSUE THREAD

**Issue by matagyula** [Nordaaker/convos#441]
The login and register screens never fully load when using Microsoft Edge.

**To Reproduce**
1. Go to your instance of Convos using Edge
2. Try to log in (/login) or register (/register)
3. The credential input fields don't show up, you get a screen saying "Convos is the simplest way to use IRC, and it keeps you always online. " with links to the documentation, etc.

**Expected behavior**
Users of Edge should be able to use Convos.

**Screenshots**
http://ks3370464.kimsufi.com:8000/file/1/qkX6xlZq1mSJPa0G.PNG

**Environment:**
 - OS: Windows 10 Pro, Version 10.0.18363 Build 18363
 - Microsoft Edge
 - Version 44.18362.449.0
 - Convos 3.08

**Additional context**
Works fine in current versions of Firefox and Vivaldi.

**Comment by jhthorsen** [comment]
I can't seem to find version 44 on browserstack.com, but I'm pretty confident it's fixed in 14db224. It won't be available until v3.10 though, unless you build Convos yourself.
