### ISSUE TITLE
/join with multiple channels creates extra channel that can't be removed

### ISSUE THREAD

**Issue by preaction** [Nordaaker/convos#442]
**Describe the bug**
When I joined multiple channels at once, an additional channel was created that I cannot leave. I created a new connection, clicked on "Add Conversation", and typed in the channels I wanted (separated by commas). When I clicked "Add", I joined all the channels I wanted.

Later, I logged back in to convos and now there is a channel called "#css,#css-ops,#css-overflow,#freenode,#mojo,#mojo-yancy" in my list of channels. When I click "Leave" for that channel, Freenode tells me I'm not in "#css", not in "#css-ops", not in "#css-overflow", etc... And the channel does not get removed from my list of channels.

**To Reproduce**
1. Go to Add Conversation
2. Type in two channels separated by a comma (`#convos,#mojo`)
3. Click "Add" and the channels are joined
4. Reload the page / log out and back in
5. There is a channel called "#convos,#mojo" in the sidebar that can't be left

**Expected behavior**
The individual channels should be joined. No extra conversation should be created.

**Screenshots**
The channels in blue don't seem to be able to be removed.
<img width="1069" alt="Screen Shot 2020-02-11 at 11 11 54 PM" src="https://user-images.githubusercontent.com/53707/74305608-0834de80-4d26-11ea-80b1-08d0a115df30.png">

**Environment:**
 - OS: Debian
 - Browser: Safari
 - Version: "stable"
 - IRC Server: freenode

**Additional context**

**Comment by preaction** [comment]
I was able to remove the problem channels by editing the `connection.json` for each network.

**Comment by jhthorsen** [comment]
I cannot reproduce this issue in master now.

**Comment by preaction** [comment]
I, too, cannot reproduce this in master. This was from the `stable` Docker image, so maybe that needs to be updated at the next release.

Thanks for looking into this!

**Comment by preaction** [comment]
Spoke too soon: My test 2 days ago worked, but this morning when I refreshed Convos the channels I joined in my test showed up as a single channel (`#mojo-foo,#mojo-bar,#mojo-baz`).
<img width="1148" alt="Screen Shot 2020-03-02 at 8 44 14 AM" src="https://user-images.githubusercontent.com/53707/75686689-49a01600-5c62-11ea-9561-69c786189663.png">

My guess is this must be getting added to the backend's data file and then only when the initial login / data sync happens does it appear again...
