### ISSUE TITLE
Bigger image previews

### ISSUE THREAD

**Issue by marcusramberg** [Nordaaker/convos#450]
As it is now, the inline image previews are so small it's often hard to make out the picture. I think they should be about twice as tall as the current ones.

**Comment by jhthorsen** [comment]
Thanks! I've been thinking the same, but I've forgotten about it.

Now I can't forget it ❤️

**Comment by jhthorsen** [comment]
I also need to update https://metacpan.org/pod/LinkEmbedder to be able to enlarge the image, since right now the embed is just a regular "rich" embed. This means if I just make the image bigger, then all the "rich" embeds will get bigger, including links to github or whatever.

**Comment by marcusramberg** [comment]
Solved now for desktop, but still too small on phones. :)
