### ISSUE TITLE
Mode changes are not shown

### ISSUE THREAD

**Issue by Svetlana-T** [Nordaaker/convos#454]
**Describe the bug**
Mode changes are not seen in the chat.

**To Reproduce**
1. Join ##convos-gry
2. Type "/mode ##convos-gry +i"

**Expected behavior**
A message to the effect of "+i was added to the channel mode of ##convos-gry "

**Screenshots**
None added

**Environment:**
 - OS: Windows 7
 - Browser: Firefox
 - Version of Convos: 3.11
 - IRC server software, name and/or version: freenode

**Additional context**
None added

**Comment by jhthorsen** [comment]
This will be part of Convos 5.25. Sorry for the long wait.
