### ISSUE TITLE
As an admin, I would like a simple way to toggle "forced_connection"

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#456]
**Describe the bug**
It used to be possible to change "forced connection" with an environment variable CONVOS_FORCED_IRC_SERVER, but this was replaced with a "forced_connection" key in $CONVOS_HOME/settings.json.

**To Reproduce**
1. Go to "Settings" in the sidebar
2. No checkbox for toggling "forced_connection"

**Comment by mrenvoize** [comment]
Sound great to me.. I wasn't aware of the forced_connection option in the settings to start with.. not sure it's documented currently.. the link on ['locked'](https://convos.by/doc/config.html#convosforcedircserver) on the convos.by page is now a dead link.
