### ISSUE TITLE
As a user, I would like to hit ESC to dismiss an image popup

### ISSUE THREAD

**Issue by amenonsen** [Nordaaker/convos#458]
I'm always frustrated when I click on an expanded image, and convos pops up a larger version, and I have to click outside the image to dismiss it, which removes focus from the text input.

I would like to be able to hit ESC and have the popup disappear and focus remain in the text box so I can keep typing messages.

**Comment by jhthorsen** [comment]
This is fixed in master, but the assets are not yet built.

Will be part of of v4.01.
