### ISSUE TITLE
Docker ARM builds

### ISSUE THREAD

**Issue by kisst** [Nordaaker/convos#464]
**Is your feature request related to a problem? Please describe.**
Would like to run convos in a Docker container on a RPi

**Describe the solution you'd like**
Setup docker hub to build multi arch setup

**Describe alternatives you've considered**
Installing it on the fly to the container, but that's not as nice

**Additional context**
Quite a few docker hub image already support it either by a separated tag, or natively in case of the official image, should be doable either way.

**Comment by jhthorsen** [comment]
Is this something you can look into @marcusramberg ?

**Comment by marcusramberg** [comment]
I've added it to my TODO, but I don't know much about what's required.

**Comment by jhthorsen** [comment]
Does not seem like we know how to do this, so I moved the issue from the 4.xx milestone to Backlog.

I hope it doesn't go into the [fridge](/Nordaaker/convos/milestone/20?closed=1).

**Comment by marcusramberg** [comment]
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ seems to have some good info on how to do this with GitHub Actions. Will investigate further.

**Comment by jhthorsen** [comment]
Looks like this won't happen without external help, so I'm placing this issue in the fridge for now.

**Comment by jhthorsen** [comment]
This is fixed in #618 🎉
