### ISSUE TITLE
Recognising half-op modes

### ISSUE THREAD

**Issue by HbombHn** [Nordaaker/convos#471]
**Describe the bug**
Users with `%`, `&` and `~` always appear as having left the channel (the username is always stricken through).

**To Reproduce**
Visit a channel with those users. `jungletrain.net`'s channel has a few people like that.
The 'left user' feature works perfectly well with the more typical modes `+` and `@`

**Expected behavior**
Those users should be accounted for the same way as oppers and voiced.

**Environment:**
 - OS: raspbian
 - Browser: Any
 - Version v4.06
 - IRC `UnrealIRCd-4.2.2` on `paranode.net` (at least for that channel)

**Comment by jhthorsen** [comment]
Thanks for reporting in! This is fixed in master now, and will be part of the upcoming release.
