### ISSUE TITLE
Highlight keywords input textfield not well updated after a tab change

### ISSUE THREAD

**Issue by thibaultduponchelle** [Nordaaker/convos#485]
**Describe the bug**
When I set Highlight keywords in settings account, it is well updated but if we change the tab and go back to settings, old value is displayed. It actually requires a page refresh to be displayed correctly.

I tried to fix by myself, but can't find the fix.

**To Reproduce**
1. Go to `settings/account`
2. Edit on `Hightlight keywords`
3. Click on `Save settings`
4. Change tab
5. Go back to `settings/account` : Old value is displayed
6. Refresh 
7. New value is displayed

**Screenshots**

Go to settings

![Screenshot from 2020-05-29 16-21-26](https://user-images.githubusercontent.com/580360/83270697-1f121a80-a1c9-11ea-8749-f4b70c49801d.png)

Edit text field
![Screenshot from 2020-05-29 16-21-39](https://user-images.githubusercontent.com/580360/83270691-1de0ed80-a1c9-11ea-8b80-c0486b02a9f8.png)

Save
![Screenshot from 2020-05-29 16-21-10](https://user-images.githubusercontent.com/580360/83270704-20434780-a1c9-11ea-8972-74756f11142b.png)

Change tab
![Screenshot from 2020-05-29 16-21-19](https://user-images.githubusercontent.com/580360/83270702-20434780-a1c9-11ea-869f-bec19f927892.png)

Back to settings (ISSUE HERE)
![Screenshot from 2020-05-29 16-21-26](https://user-images.githubusercontent.com/580360/83270697-1f121a80-a1c9-11ea-8749-f4b70c49801d.png)

Refresh
![Screenshot from 2020-05-29 16-21-32](https://user-images.githubusercontent.com/580360/83270695-1f121a80-a1c9-11ea-96c0-90d815c746a2.png)

Finally OK
![Screenshot from 2020-05-29 16-21-06](https://user-images.githubusercontent.com/580360/83270707-20dbde00-a1c9-11ea-90a0-2763138af35b.png)

**Comment by jhthorsen** [comment]
Thanks! 👍

**Comment by thibaultduponchelle** [comment]
👍 😃
