### ISSUE TITLE
Build installable packages

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#491]
I wonder if we’d should consider building more packages. I’m thinking...

* deb
* rpm

Would anyone be interested in this? If so, would you also help me figure out how to do it?

**Comment by stigtsp** [comment]
A nix package and service has been created, and is waiting to be reviewed. Feel free to test it :) https://github.com/NixOS/nixpkgs/pull/88940

When it's (hopefully) accepted you'll be able to set it up on NixOS using:
```
services.convos.enable=true;
```

Or install it imperatively using Nix (on Linux/Darwin) using:
```
$ nix-env -Ai nixpkgs.convos
```

**Comment by jhthorsen** [comment]
This issue is actually a duplicate of #326. I had forgotten about that one.

**Comment by jhthorsen** [comment]
Going to put this in the fridge, since I don't think I will put too much effort into it, unless someone asks / provides a PR.
