### ISSUE TITLE
can't see users in the channel.

### ISSUE THREAD

**Issue by TimeRider07** [Nordaaker/convos#497]
When I am connected to the server and port (SSL), I can't see the connected users in the channel.

It just shows me alone as the participant (even though there are users in the channel).

And when someone joins the channel, then it becomes 2 participants and so on.

What could be the error?

**Comment by jhthorsen** [comment]
There's not enough details for me to investigate this. I connection information (like server name, port, ...) and maybe even the channel that fails.

**Comment by TimeRider07** [comment]
Server is: irc.chatsansar.com
Port (ssl): +6697
Convos link: https://chatsansar.com/cloud

If you check it?
Thank you!

**Comment by jhthorsen** [comment]
I just joined #Nepal and I see 75 people in that channel.

**Comment by TimeRider07** [comment]
Okay, I have just snapped a screenshot of what goes when I sign up as new user "suraj@gmail.com" and go to chat.
screenshot: [https://chatsansar.com/convos/convos%20error.JPG](url)

**Comment by jhthorsen** [comment]
I'm guessing this is related to #496.
