### ISSUE TITLE
Support temporary connections

### ISSUE THREAD

**Issue by tehmoth** [Nordaaker/convos#499]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A class of users should be temporary, i.e. non persistent connections, Convos should close the irc connection after a certain (configurable) amount of time after the websocket is downed (not if the browser tag is closed or refreshed).   Once User Administration is added, upgrading and downgrading users to and from permanent connections should be possible.

**Comment by salehur** [comment]
This is a great idea. Thanks Convos for your support.

**Comment by jhthorsen** [comment]
@salehur: The request is just about taking down actual connection, while keeping the user account.

For sake of reference, I'm going to mention #417, which is for "user admin".

**Comment by jhthorsen** [comment]
I don’t picture myself working on this, so I’m afraid I have to put this in the “Fridge”. I don’t mind a PR though 👍

I’m not entirely sure, but it might be implemented when we work on #346.

**Comment by jberger** [comment]
This would relate to #546 nicely
