### ISSUE TITLE
Disk usage check might be failing on zfs?

### ISSUE THREAD

**Issue by stigtsp** [Nordaaker/convos#504]
Not sure if it's on zfs, but sounds like it :)

This happens on nixpkgs hydra (aarch64):

```
t/web-admin.t .................... 1/? 
#   Failed test 'similar match for JSON Pointer "/disk_usage/dev"'
#   at t/web-admin.t line 28.
#                   'rpool/root'
#     doesn't match '(?^:/dev/)'
Use of uninitialized value in pattern match (m//) at /build/source/blib/lib/Convos/Controller/Admin.pm line 50.
# Looks like you failed 1 test of 63.
t/web-admin.t .................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/63 subtests 
```

https://logs.nix.ci/?key=nixos/nixpkgs.92702&attempt_id=00a6e425-c116-4071-8784-7e4a023e1102

https://github.com/NixOS/nixpkgs/pull/92702

**Comment by jhthorsen** [comment]
Thanks for the issue! "master" is a bit in limbo now, so maybe you should wait for 4.24 before building a new version.
