### ISSUE TITLE
Add connection with conversation name does not join conversation room

### ISSUE THREAD

**Issue by thibaultduponchelle** [Nordaaker/convos#512]
**Describe the bug**
When using the "Add conversation" tab to open/connect a new server and join a room, the room is not joined.

**To Reproduce**
1. Go to 'Add connection'
![addconnectiontab](https://user-images.githubusercontent.com/580360/91944042-c25d5900-ecfd-11ea-8d3f-aa58ab19d598.png)
2. Fill in the server with "irc.amigaworld.net" (for instance)
3. Fill in the room with "#amigaworld"
![addconnection](https://user-images.githubusercontent.com/580360/91944195-fc2e5f80-ecfd-11ea-8547-c0780c047b71.png)
4. Click on "Create"
3. Go to "amigaworld" server tab
4. See error : only NickServ conversation is opened
![serverandnickserv](https://user-images.githubusercontent.com/580360/91944301-27b14a00-ecfe-11ea-83bf-5c5e29dcfa49.png)

**Details**
In the server connection logs, the "/join #amigaworld" well appears : 
![slashjoin](https://user-images.githubusercontent.com/580360/91944800-f1c09580-ecfe-11ea-9887-69bc039ea293.png)

In the server connection log, here are the details of the "/join #amigaworld" : 
![logko](https://user-images.githubusercontent.com/580360/91944396-4ca5bd00-ecfe-11ea-89b1-bd81a13e40f1.png)

After a manual "/join #amigaworld" we join correctly the room and we have these details in the server connection log : 
![logokafterjoin](https://user-images.githubusercontent.com/580360/91944481-6c3ce580-ecfe-11ea-97d5-81fad5f4c30b.png)

**Expected behavior**
Open connection to server AND join specified room (or remove conversation name in the form).

**Environment:**
 - Latest convos (and some previous versions also)

Thank you a lot ! :) :)

**Comment by jhthorsen** [comment]
Thanks for the detailed bug report! This is now fixed in "master" and will be part of the 4.37 release.
