### ISSUE TITLE
Admin password recovery

### ISSUE THREAD

**Issue by zexa** [Nordaaker/convos#516]
Hi, 

I have a single admin user setup that I use at home but I seem to have forgotten my password. How can I reset the password without losing any data assuming i have root access in the environment convos is running in?

**Comment by jhthorsen** [comment]
The command is documented here: https://convos.chat/blog/2019/11/24/convos-one-point-two

Scroll down to “Forgotten password and invitation links”

I’ll keep this issue open, since this should also be in the FAQ.

**Comment by jhthorsen** [comment]
This is now documented in the "Configuration" page instead.
