### ISSUE TITLE
Need to replace "dialog" with a better noun

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#519]
I just got to know that a "dialog" refers to a "dialog box" and not a *dialogue*.

Because of this, I want to rename "dialog" everywhere in the code. This will be a breaking change, since it will affect both the API, class names, attributes and svelte components.

My suggestions are "room" or "conversation". The new word need to cover one-to-one, server messages and multi participant rooms. The "server" case is probably the reason why I didn't settle on "room" in the first place, but maybe it's not too bad..? I don't want "messages", since it sounds like just a list of messages. I'm not a huge fan of "Chat" or "Channel", but please do convince me if that's a good idea.

Another reason to call it a "conversation" is because the UI use "Conversations", "Add conversation", ...

So here is a summary of the naming suggestions:

* Conversation
* Room
* Dialogue
* Chat
* Channel

Other suggestions?

**Comment by shadowcat-mst** [comment]
Wait. This was me.

'dialog' is apparently a perfectly acceptable en_US spelling of 'dialogue'.

So my apologies for not realising that (I just went and dug into dictionaries) and I don't think you need to worry.

**Comment by shadowcat-mst** [comment]
Note though that Grinnz is definitely USian and didn't find it idiomatic.

irssi uses "window" (or more precisely "windowitem") for this, though I guess that doesn't really fit convos.

I sort of feel like "channel" might be ok if you think of it in terms of a go or IO::Async channel, i.e. something you send/receive messages from rather than the IRC meaning, but being an IRC client that's not necessarily ideal either.

**Comment by jhthorsen** [comment]
“Channel” sounds more like a “bus” or something that you pass messages through, rather than an object.

I think “conversation” is the winner so far, since it’s also reflected in the UI: There’s “Add conversation” in the menu and also “Conversations” as a heading.

**Comment by Grinnz** [comment]
Conversation seems the most widely applicable to me. "Room" and "channel" are a bit odd for referring to private messages.

**Comment by jhthorsen** [comment]
This will get merged when I merge the [next](https://github.com/Nordaaker/convos/compare/next) branch tomorrow morning.

- 8d888dd00699564c69fe25e5f4baf9188b8c9a21 - Renamed from "dialog" to "conversation" #519
- aafc1e0a764475b330729b0e3ead984c65f1f6b6 - Add back compat code for loading "dialogs" from connection.json
- 958e89741f3479e41f1f7b1bcd1062892aa0f896 - Updated Changes

**Comment by jhthorsen** [comment]
Thanks for all the help!
