### ISSUE TITLE
Cached Version on Update

### ISSUE THREAD

**Issue by wylel** [Nordaaker/convos#539]
**Describe the bug**
When updating, upon success the version will show the last updated version instead of the newly installed version.

**To Reproduce**
1. Update
2. Upon success, updated version shows last version updated and not new version.

**Expected behavior**
See newest version installed by the update command.

**Environment:**
Any as far as I know.

**Additional context**
Posting as issue so batman knows to fix it :D

**Comment by jhthorsen** [comment]
This is fixed in master now, but since you need to upgrade to the new version to get the fix then you have to wait until next-next version to see the fix.
