### ISSUE TITLE
Loading multiple avatars in desktop view slows down the client

### ISSUE THREAD

**Issue by ivan-avalos** [Nordaaker/convos#554]
**Describe the bug**
In large rooms, the client slows down because it has to load all the avatars. This only seems to happen in desktop view, when Participants list is visible, along with user avatars.

**To Reproduce**
1. Go to a large room (e.g. #kde) on a large screen.
2. See performance issues as the command `/users` is loading.
3. See the yellow banner (in Firefox) saying "A web page is slowing down your browser".
4. Notice that shouldn't happen.

**Expected behavior**
There shouldn't be significant performance issues when loading a large amount of user avatars.

**Environment:**
 - OS: Manjaro ARM, Linux 5.10
 - Browser: Mozilla Firefox
 - Version: 84.0
 - IRC server software, name and/or version: Oragono 2.4.0.

**Additional context**
I'm experiencing the problem in my Pinebook Pro, which is not a very powerful computer, but this shouldn't happen anyway, there has to be some caching for avatars. The process of computing and loading avatars should be more efficient.

**Comment by jhthorsen** [comment]
I'm not entirely sure how to fix this, but I wonder if it could be as simple as just showing the first 200 (?) participants and a "search" field. I'm not too fond of adding the search field though, so if anyone has input, then please let me know.

*Maybe* this is a good opportunity to add something like https://gitlab.com/catamphetamine/virtual-scroller

**Comment by ivan-avalos** [comment]
Fixed on v5.16!

**Comment by jhthorsen** [comment]
The fix was caused by adding https://github.com/Nordaaker/convos/commit/8290b5313fcf418b691c1e48a082ccb6fed97e38#diff-c7f96b376f69fdc3cf178c699a4aef95339f1b2f8023a5545ef52acdf61c89ed

The change only updates the participant list, which is a local change instead of updating the whole user interface like it used to, when the participant list was part of store/Conversation.js
