### ISSUE TITLE
Option to disable conversion of emoticons to emoji

### ISSUE THREAD

**Issue by WesleyAC** [Nordaaker/convos#555]
I don't like the automatic conversion of emoticons (like `:)`) to emoji (🙂). It would be great to have a per-user option to disable this conversion.

**Comment by WesleyAC** [comment]
As discussed on #convos, a lone `://` will get converted into ":confused:/", which is typically not intended. I ran into this when someone was talking about the `://` in `http://`, in the following message:

```
wouldn't it need :// too?
like proto://user@domain.com
```

this seems like a bug

**Comment by jhthorsen** [comment]
I closed this by fixing the regexp for turning ":/" into a smiley.
