### ISSUE TITLE
Auto-rejoin channels that fail on server connect

### ISSUE THREAD

**Issue by WesleyAC** [Nordaaker/convos#557]
**Is your feature request related to a problem? Please describe.**

I am in a few invite-only and identified-only channels on freenode (`+i`/`+r`). When the server disconnects, and then reconnects, it fails to join these channels, and once I've identified with NickServ, I need to `/join` each channel individually again.

**Describe the solution you'd like**

I think an ideal solution would be to retry joining channels for which joins failed on connecting to the server, possibly with some sort of exponential backoff. This is the solution that ZNC uses. This avoids needing to know about what channel modes mean, what NickServ is, etc. Presumably there's some thinking that needs to be done about what the right behaviour is with `/kick`, etc. A reasonable conservative approach might be to just do the retrying if joining a channel fails immediately after connecting to the server.

**Describe alternatives you've considered**

If there's interest in an extension that integrates with NickServ, this could be done slightly more cleanly, but IMO it makes sense to auto-rejoin channels

**Comment by jhthorsen** [comment]
Why don't you identify with nickserv on connect instead?

**Comment by WesleyAC** [comment]
Is there an option that will do that? I would be fine with that as a solution, but I don't know whether convos should make assumptions about NickServ.

**Comment by jhthorsen** [comment]
The connection setting allows you to authenticate and/or run commands when you connect.

![Screenshot_2021-01-24 Better group chat](https://user-images.githubusercontent.com/45729/105629361-e9bbea80-5e85-11eb-9619-dc59a87f74a8.png)
