### ISSUE TITLE
Scrollback fails to load intermittently

### ISSUE THREAD

**Issue by WesleyAC** [Nordaaker/convos#558]
**Describe the bug**

Sometimes, when I click on a channel, I cannot load the scrollback by scrolling up. I think this is at least somewhat related to the theme I'm using, which can be found [here](https://hack.wesleyac.com/convos-neckbeard.css). This problem typically, although not exclusively happens when the chat window is sized such that there is no scrollbar.

I tried changing [this code](https://github.com/Nordaaker/convos/blob/442e5db35fca1f93a6b95177c42e130f8ba29ca8/assets/store/Conversation.js#L126), changing the `30` and `40` both to `60`, which has stopped the chat window from loading such that it is impossible to scroll, but I still have the problem that scrolling up does not always load the scrollback.

Resizing my browser window vertically consistently "fixes" the issue, and clicking on a different channel then back on the original channel occasionally fixes it.

My screen is 1920x1080, although browser chrome takes up some of that space.

**To Reproduce**
1. Install theme linked above
2. Click on a channel
3. Attempt to scroll up
4. Scrollback does not load

**Expected behavior**
Scrollback loads.

**Screenshots**

![2021-01-22_21 29 35_1642x961](https://user-images.githubusercontent.com/5001092/105500667-28269d80-5cfe-11eb-8020-70d1f15e4514.png)

(note that there is no scrollbar in the image)

**Environment:**
 - OS: NixOS Linux
 - Browser: Firefox 84.0.2
 - Version: v5.11

**Comment by WesleyAC** [comment]
Oh, something important to add: I have the "Enable compact message display" setting enabled.

**Comment by jhthorsen** [comment]
This will be part of the 5.23 release.
