### ISSUE TITLE
URL expansion not respecting Account Settings

### ISSUE THREAD

**Issue by rabbiveesh** [Nordaaker/convos#562]
**Describe the bug**
Convos (since 5.15 at least) has been ignoring my setting to not expand URLs to media by default

**To Reproduce**
1. go to "Account"
2. turn off "Expand URLs to media"
3. save

**Expected behavior**
URLs should not expand to media

**Environment:**
 - OS: ubuntu 20.04
 - Browser firefox
 - Version 5.15 and up
 - on all connections

**Additional context**
I looked at the console, and when I save my account settings, the only thing sent in the request is `highlight_keywords`. This is whether or not expand URLs to media is checked.

I'd be happy to fix this if you could point me in the right direction, by the way.

**Comment by jhthorsen** [comment]
Thanks for reporting in! This was caused of a rather big refactor I did last weekend. Will be fixed in the next release.
