### ISSUE TITLE
Add support for being invited to a channel

### ISSUE THREAD

**Issue by jberger** [Nordaaker/convos#568]
I don't know what is involved to add this feature, but it does seem that it isn't the ircv3 invite-notify (and the website says freenode doesn't support that anyway). I do know that in trying to join an invite-only channel I got a server error `Unhandled rejected promise: Cannot join channel (+i) - you must be invited at /app/local/lib/perl5/Mojo/Reactor/Poll.pm line 129` and then when I was invited it only showed as `#thechannelname` in the network log, which didn't help me realize I'd been invited. 

I would like it if there was better notification that an invite was required and have some indication that I'd been invited, hopefully with the option given to then join the channel as a direct result.

**Comment by jhthorsen** [comment]
This will be part of 5.30:

<img width="376" alt="Screen Shot 2021-02-20 at 15 24 29" src="https://user-images.githubusercontent.com/45729/108586122-bb9bce80-738f-11eb-9dc7-0ac761f30e14.png">

Working on handling invites as well. Updates will come soon...

**Comment by jhthorsen** [comment]
You will get a desktop notification and a conversation in the sidebar now. When clicking on the pending channel, you will see this:

<img width="376" alt="Screen Shot 2021-02-20 at 16 30 56" src="https://user-images.githubusercontent.com/45729/108587783-04a45080-7399-11eb-9fe4-9a20669471d3.png">

**Comment by jberger** [comment]
\o/
