### ISSUE TITLE
frame/iframe on the video call page cuts the image

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [Nordaaker/convos#570]
**Describe the bug**
When opening a video call with `jitsi` (default) unless we choose to go full screen the `frame/iframe` cuts the image

**To Reproduce**
1. Go to any channel/pm
2. Click on the camera icon
3. See the page that opens with the video call

**Expected behavior**
The `frame/iframe` should use the entire screen.

**Screenshots**
See end of the post

**Environment:**
 - OS: Xubuntu
 - Browser Chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

![video_call](https://user-images.githubusercontent.com/25697531/108234004-a5e69900-7144-11eb-945e-c3105f1068d7.png)

**Comment by jhthorsen** [comment]
Thanks for reporting in!

This should be fixed in the upcoming 5.28 release.
