### ISSUE TITLE
Create pluggable authentication support

### ISSUE THREAD

**Issue by jhthorsen** [Nordaaker/convos#89]
I want to use https://metacpan.org/release/Mojolicious-Plugin-Web-Auth to do oauth and oauth2 authentication.

@marcusramberg wants to use https://metacpan.org/release/Mojolicious-Plugin-OAuth2.

The reason I want to use Web::Auth is that it supports both oauth and oauth2. What do you think @marcusramberg?

I also want to make this an optional module.

**Comment by jhthorsen** [comment]
I want to add support @jberger's https://metacpan.org/pod/Mojo::JWT module instead. I can be very nice for inviting people to chat, instead of using the invite code that is implemented today.

**Comment by s1037989** [comment]
:+1: to that!  Mojo::JWT is super cool!

I can totally see it being perfect for invite codes, but how do you see it as an alternative to OAuth2?  My understanding is that you use OAuth2 to allow another, bigger, provider such as GitHub and Facebook to handle authentication.  It keeps the responsibility of passwords off of your system (yes?) and it centralizes credentials for users.  In this scenario, I just sign in to Convos with my Github account.  Easy!

With JWT...  what do you envision happening?

**Comment by jhthorsen** [comment]
Closing this issue for now since the plugin is created. What need to be done later is to have the possibility to customise which elements that should be visible on the login/register page.

@s1037989: It's not really an alternative. I just don't fancy Oauth2 too much to bother to implement it. At least not for now.

Going to revisit it later, when I see how invitation links with JWT can mak the onboarding much smoother.

**Comment by poVoq** [comment]
@jhthorsen any chance the situation regarding login via OpenID Connect / Oauth2 can be revisited?

**Comment by jhthorsen** [comment]
I have a hard time seeing how that would work. Let's say if I you add support for Facebook, how would you limit who could register?

**Comment by poVoq** [comment]
Maybe that would be the point? Open registration :)

But actually there are a lot of selfhosted services that offer OIDC server/provider functionality, such as Nextcloud and Gitea. Thus one could manage the users through those systems and allow people to also log into Convos that way.

**Comment by jhthorsen** [comment]
@poVoq: Could you open a new issue with the description of how you picture this to work? I don't want to reopen this issue, since it has gotten very messy 😞
